import { getRows,SHEETS } from "@/lib/sheets";
const bool=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1";
const num=(v:any)=>v==null||v===""?0:Number(v);
export async function catalogueLookups(){
 const [authors,publishers,categories,subjects,levels,curricula,classes]=await Promise.all([getRows(SHEETS.catalogueAuthors),getRows(SHEETS.cataloguePublishers),getRows(SHEETS.catalogueCategories),getRows(SHEETS.catalogueSubjects),getRows(SHEETS.catalogueAcademicLevels),getRows(SHEETS.catalogueCurricula),getRows(SHEETS.catalogueClasses)]);
 const active=(rows:any[])=>rows.filter(r=>bool(r.IsActive??true)).sort((a,b)=>String(a.Name).localeCompare(String(b.Name)));
 return {authors:active(authors),publishers:active(publishers),categories:active(categories),subjects:active(subjects),levels:active(levels),curricula:active(curricula),classes:active(classes)};
}
export async function listProducts(filters:{q?:string;type?:string;status?:string;categoryId?:string}={}){
 const [products,books,publishers,categories,barcodes]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.catalogueBooks),getRows(SHEETS.cataloguePublishers),getRows(SHEETS.catalogueCategories),getRows(SHEETS.catalogueBarcodes)]);
 const q=(filters.q||"").trim().toLowerCase();
 return products.map(p=>{const book=books.find(b=>b.ProductId===p.Id);return {...p,IsActive:bool(p.IsActive),IsBook:String(p.ProductType).toUpperCase()==="BOOK",CostPrice:num(p.CostPrice),SellingPrice:num(p.SellingPrice),PublisherName:publishers.find(x=>x.Id===book?.PublisherId)?.Name||"",CategoryName:categories.find(x=>x.Id===p.CategoryId)?.Name||"",ISBN13:book?.ISBN13||"",ISBN10:book?.ISBN10||"",Barcode:barcodes.find(x=>x.ProductId===p.Id&&bool(x.IsPrimary??true))?.Barcode||""}}).filter(p=>(!q||[p.Code,p.Name,p.ISBN13,p.ISBN10,p.Barcode,p.PublisherName,p.CategoryName].some(v=>String(v||"").toLowerCase().includes(q)))&&(!filters.type||filters.type==="ALL"||p.ProductType===filters.type)&&(!filters.status||filters.status==="ALL"||(filters.status==="ACTIVE"?p.IsActive:!p.IsActive))&&(!filters.categoryId||p.CategoryId===filters.categoryId)).sort((a,b)=>String(b.CreatedAt||"").localeCompare(String(a.CreatedAt||"")));
}
export async function getProduct(id:string){
 const [products,books,authors,publishers,categories,subjects,levels,pa,barcodes,prices]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.catalogueBooks),getRows(SHEETS.catalogueAuthors),getRows(SHEETS.cataloguePublishers),getRows(SHEETS.catalogueCategories),getRows(SHEETS.catalogueSubjects),getRows(SHEETS.catalogueAcademicLevels),getRows(SHEETS.catalogueProductAuthors),getRows(SHEETS.catalogueBarcodes),getRows(SHEETS.cataloguePriceHistory)]);
 const product=products.find(p=>p.Id===id);if(!product)return null;const book=books.find(b=>b.ProductId===id);const authorIds=pa.filter(x=>x.ProductId===id&&bool(x.IsActive??true)).map(x=>x.AuthorId);
 return {product:{...product,IsActive:bool(product.IsActive),TrackInventory:bool(product.TrackInventory),CostPrice:num(product.CostPrice),SellingPrice:num(product.SellingPrice),ReorderLevel:num(product.ReorderLevel),SafetyStock:num(product.SafetyStock)},book,authors:authors.filter(a=>authorIds.includes(a.Id)),publisher:publishers.find(x=>x.Id===book?.PublisherId)||null,category:categories.find(x=>x.Id===product.CategoryId)||null,subject:subjects.find(x=>x.Id===book?.SubjectId)||null,academicLevel:levels.find(x=>x.Id===book?.AcademicLevelId)||null,barcodes:barcodes.filter(x=>x.ProductId===id&&bool(x.IsActive??true)),priceHistory:prices.filter(x=>x.ProductId===id).sort((a,b)=>String(b.EffectiveFrom||b.CreatedAt).localeCompare(String(a.EffectiveFrom||a.CreatedAt))).slice(0,20)};
}
export async function catalogueSummary(){const rows=await listProducts();return {total:rows.length,active:rows.filter(x=>x.IsActive).length,books:rows.filter(x=>x.IsBook).length,other:rows.filter(x=>!x.IsBook).length,missingBarcode:rows.filter(x=>!x.Barcode&&!x.ISBN13).length}}
export async function listMaster(sheet:keyof Pick<typeof SHEETS,'catalogueAuthors'|'cataloguePublishers'|'catalogueCategories'|'catalogueSubjects'|'catalogueAcademicLevels'>){return (await getRows(SHEETS[sheet])).map(r=>({...r,IsActive:bool(r.IsActive??true)})).sort((a,b)=>String(a.Name).localeCompare(String(b.Name)))}
