import { cookies } from "next/headers";
import crypto from "crypto";
import { usingGoogleSheets } from "@/lib/data-provider";
import { hashPassword,verifyPassword } from "@/lib/password";
import { writeLoginHistory } from "@/lib/audit";
import { gsCreateSession,gsCreateUser,gsFindUserByEmail,gsLoadIdentity,gsRevokeUserSessions } from "@/data/google-services";
import { getRows,SHEETS,updateRow } from "@/lib/sheets";
import * as sqlAuth from "@/data/providers/sql-server/legacy/auth-lib";
const COOKIE="risdel_session";
export type Session={userId:string|null;email:string;name:string;role:string;roleCode:string;permissions:string[];mustChangePassword:boolean;source:"database"|"bootstrap";exp:number};
function secret(){return process.env.AUTH_SECRET||"development-secret-change-me-please-32chars"}
function sign(payload:string){return crypto.createHmac("sha256",secret()).update(payload).digest("base64url")}
function encode(s:Session){const body=Buffer.from(JSON.stringify(s)).toString("base64url");return `${body}.${sign(body)}`}
function decode(token?:string):Session|null{if(!token)return null;const [body,sig]=token.split(".");if(!body||!sig)return null;const expected=sign(body);if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;try{const s=JSON.parse(Buffer.from(body,"base64url").toString()) as Session;return s.exp>Date.now()?s:null}catch{return null}}
function safeEqual(a:string,b:string){const aa=Buffer.from(a.padEnd(256));const bb=Buffer.from(b.padEnd(256));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb)}
export function validateBootstrapCredentials(email:string,password:string){const e=process.env.BOOTSTRAP_ADMIN_EMAIL||"admin@risdel.local";const p=process.env.BOOTSTRAP_ADMIN_PASSWORD||"ChangeMe@123";return safeEqual(email.toLowerCase(),e.toLowerCase())&&safeEqual(password,p)}
async function setGoogleSession(session:Omit<Session,"exp">,remember=false){const hours=remember?Number(process.env.REMEMBER_SESSION_HOURS||168):Number(process.env.SESSION_HOURS||8);const exp=Date.now()+hours*3600_000;const full={...session,exp};const token=encode(full);const store=await cookies();store.set(COOKIE,token,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",expires:new Date(exp)});if(session.userId)try{await gsCreateSession(session.userId,crypto.createHash("sha256").update(token).digest("hex"),new Date(exp))}catch(error){console.error("Unable to persist session metadata",error)}}
export async function authenticate(email:string,password:string,remember=false){if(!usingGoogleSheets())return sqlAuth.authenticate(email,password,remember);try{let user=await gsFindUserByEmail(email);if(!user&&validateBootstrapCredentials(email,password)){const roles=await getRows(SHEETS.roles);const superRole=roles.find(r=>r.Code==="SUPER_ADMIN");if(!superRole)return {ok:false,error:"Google Sheets is not initialized. Run npm run sheets:init first."} as const;const id=await gsCreateUser({email,name:process.env.BOOTSTRAP_ADMIN_NAME||"System Administrator",hash:await hashPassword(password),roleId:superRole.Id});user=await gsFindUserByEmail(email);if(!user)return {ok:false,error:"Unable to provision bootstrap administrator."} as const;await updateRow(SHEETS.users,id,{MustChangePassword:true})}
if(!user)return {ok:false,error:"Invalid email or password."} as const;if(String(user.IsActive).toLowerCase()==="false"||user.IsActive===false){await writeLoginHistory(email,false,String(user.Id),"Account inactive");return {ok:false,error:"This account is inactive. Contact an administrator."} as const}if(user.LockedUntil&&new Date(user.LockedUntil)>new Date()){await writeLoginHistory(email,false,String(user.Id),"Account locked");return {ok:false,error:"Account temporarily locked because of repeated failed sign-in attempts."} as const}if(!await verifyPassword(password,user.PasswordHash)){const failed=Number(user.FailedLoginCount||0)+1,max=Number(process.env.LOGIN_MAX_ATTEMPTS||5),lockMinutes=Number(process.env.LOGIN_LOCK_MINUTES||15);await updateRow(SHEETS.users,String(user.Id),{FailedLoginCount:failed,LockedUntil:failed>=max?new Date(Date.now()+lockMinutes*60000).toISOString():user.LockedUntil||"",UpdatedAt:new Date().toISOString()});await writeLoginHistory(email,false,String(user.Id),"Invalid password");return {ok:false,error:"Invalid email or password."} as const}await updateRow(SHEETS.users,String(user.Id),{FailedLoginCount:0,LockedUntil:"",LastLoginAt:new Date().toISOString(),UpdatedAt:new Date().toISOString()});const identity=await gsLoadIdentity(String(user.Id));if(!identity)return {ok:false,error:"Unable to load account permissions."} as const;await setGoogleSession(identity,remember);await writeLoginHistory(email,true,String(user.Id));return {ok:true,mustChangePassword:identity.mustChangePassword} as const}catch(error){console.error("Google Sheets authentication failed",error);return {ok:false,error:"Authentication service is temporarily unavailable. Check the Google Sheets connection."} as const}}
export async function getSession(){if(!usingGoogleSheets())return sqlAuth.getSession();const store=await cookies();const session=decode(store.get(COOKIE)?.value);if(!session)return null;if(session.userId){try{const identity=await gsLoadIdentity(session.userId);if(!identity){await clearSession();return null}return {...session,...identity}}catch{return session}}return session}
export async function clearSession(){if(!usingGoogleSheets())return sqlAuth.clearSession();const store=await cookies();const s=decode(store.get(COOKIE)?.value);if(s?.userId)try{await gsRevokeUserSessions(s.userId)}catch{}store.set(COOKIE,"",{httpOnly:true,path:"/",expires:new Date(0)})}
