import {getRows,SHEETS} from "@/lib/sheets";
const yes=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1"; const n=(v:any)=>Number(v||0);
export const money=(v:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(v||0);
export async function academicLookups(){const [customers,sessions,terms,classes,products,books,balances,schools]=await Promise.all([getRows(SHEETS.salesCustomers),getRows(SHEETS.catalogueAcademicSessions),getRows(SHEETS.catalogueTerms),getRows(SHEETS.catalogueClasses),getRows(SHEETS.catalogueProducts),getRows(SHEETS.catalogueBooks),getRows(SHEETS.inventoryBalances),getRows(SHEETS.academicSchools)]);return {customers:customers.filter(x=>yes(x.IsActive??true)&&String(x.CustomerType)==="SCHOOL"),sessions:sessions.filter(x=>yes(x.IsActive??true)),terms:terms.filter(x=>yes(x.IsActive??true)),classes:classes.filter(x=>yes(x.IsActive??true)),products:products.filter(x=>yes(x.IsActive??true)&&String(x.Status||"ACTIVE")!=="INACTIVE"),books,balances,schools:schools.filter(x=>yes(x.IsActive??true))};}
export async function listSchools(){const [schools,customers,lists,orders]=await Promise.all([getRows(SHEETS.academicSchools),getRows(SHEETS.salesCustomers),getRows(SHEETS.academicBookLists),getRows(SHEETS.academicOrders)]);return schools.filter(x=>yes(x.IsActive??true)).map(s=>{const c=customers.find(x=>x.Id===s.CustomerId)||{};const so=orders.filter(o=>o.SchoolId===s.Id&&yes(o.IsActive??true));return {...s,CustomerName:c.Name||s.SchoolName,Phone:c.Phone||"",Email:c.Email||"",BookListCount:lists.filter(l=>l.SchoolId===s.Id&&yes(l.IsActive??true)).length,OrderCount:so.length,OrderValue:so.reduce((a,o)=>a+n(o.Total),0)}}).sort((a,b)=>String(a.CustomerName).localeCompare(String(b.CustomerName)));}
export async function listBookLists(){const [lists,items,schools,customers,sessions,classes]=await Promise.all([getRows(SHEETS.academicBookLists),getRows(SHEETS.academicBookListItems),getRows(SHEETS.academicSchools),getRows(SHEETS.salesCustomers),getRows(SHEETS.catalogueAcademicSessions),getRows(SHEETS.catalogueClasses)]);return lists.filter(x=>yes(x.IsActive??true)).map(l=>{const school=schools.find(s=>s.Id===l.SchoolId),customer=customers.find(c=>c.Id===school?.CustomerId);const its=items.filter(i=>i.BookListId===l.Id&&yes(i.IsActive??true));return {...l,SchoolName:customer?.Name||school?.SchoolName||"—",SessionName:sessions.find(s=>s.Id===l.SessionId)?.Name||"—",ClassName:classes.find(c=>c.Id===l.ClassId)?.Name||"—",ItemCount:its.length,EstimatedTotal:its.reduce((a,i)=>a+n(i.Quantity)*n(i.UnitPrice),0)}}).sort((a,b)=>String(b.UpdatedAt||b.CreatedAt).localeCompare(String(a.UpdatedAt||a.CreatedAt)));}
export async function listOrders(){const [orders,schools,customers,lines]=await Promise.all([getRows(SHEETS.academicOrders),getRows(SHEETS.academicSchools),getRows(SHEETS.salesCustomers),getRows(SHEETS.academicOrderLines)]);return orders.filter(x=>yes(x.IsActive??true)).map(o=>{const s=schools.find(x=>x.Id===o.SchoolId),c=customers.find(x=>x.Id===s?.CustomerId);return {...o,SchoolName:c?.Name||s?.SchoolName||"—",LineCount:lines.filter(l=>l.OrderId===o.Id&&yes(l.IsActive??true)).length,Total:n(o.Total),AmountPaid:n(o.AmountPaid),BalanceDue:n(o.BalanceDue)}}).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt)));}
export async function availability(){const [products,books,balances,items,lists,schools,customers]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.catalogueBooks),getRows(SHEETS.inventoryBalances),getRows(SHEETS.academicBookListItems),getRows(SHEETS.academicBookLists),getRows(SHEETS.academicSchools),getRows(SHEETS.salesCustomers)]);return items.filter(x=>yes(x.IsActive??true)).map(i=>{const p=products.find(x=>x.Id===i.ProductId)||{},b=books.find(x=>x.ProductId===i.ProductId)||{},l=lists.find(x=>x.Id===i.BookListId),s=schools.find(x=>x.Id===l?.SchoolId),c=customers.find(x=>x.Id===s?.CustomerId);const on=balances.filter(x=>x.ProductId===i.ProductId&&yes(x.IsActive??true)).reduce((a,x)=>a+n(x.QuantityOnHand)-n(x.QuantityReserved)-n(x.QuantityDamaged),0),req=n(i.Quantity);return {Id:i.Id,ProductId:i.ProductId,ProductName:p.Name||"—",ISBN:b.ISBN13||b.ISBN10||"—",SchoolName:c?.Name||"—",ListName:l?.Name||"—",Required:req,Available:on,Status:on<=0?"OUT OF STOCK":on<req?"PARTIAL":"AVAILABLE"}});}
export async function academicSummary(){const [schools,lists,orders,av]=await Promise.all([listSchools(),listBookLists(),listOrders(),availability()]);return {schools:schools.length,lists:lists.length,orders:orders.length,orderValue:orders.reduce((a,o)=>a+o.Total,0),openOrders:orders.filter(o=>!["COMPLETED","CANCELLED"].includes(String(o.Status))).length,outOfStock:av.filter(x=>x.Status==="OUT OF STOCK").length,partial:av.filter(x=>x.Status==="PARTIAL").length};}
