import {cookies} from "next/headers";
import crypto from "crypto";
import {getRows,SHEETS} from "@/lib/sheets";
import {resolvePrice} from "@/features/pricing/data";
import {verifyPassword} from "@/lib/password";
const bool=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1";const num=(v:any)=>Number(v||0);export const money=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(n||0);
const PORTAL_COOKIE="risdel_portal";function secret(){return process.env.AUTH_SECRET||"development-secret-change-me-please-32chars"}function sign(v:string){return crypto.createHmac("sha256",secret()).update(v).digest("base64url")}
export function encodePortal(accountId:string){const body=Buffer.from(JSON.stringify({accountId,exp:Date.now()+30*24*3600_000})).toString("base64url");return `${body}.${sign(body)}`}
export async function portalSession(){const c=await cookies(),token=c.get(PORTAL_COOKIE)?.value;if(!token)return null;const [body,sig]=token.split(".");if(!body||!sig||sign(body)!==sig)return null;try{const x=JSON.parse(Buffer.from(body,"base64url").toString());if(x.exp<Date.now())return null;const accounts=await getRows(SHEETS.commercePortalAccounts);const account=accounts.find(a=>a.Id===x.accountId&&bool(a.IsActive??true));if(!account)return null;const customers=await getRows(SHEETS.salesCustomers);return {account,customer:customers.find(c=>c.Id===account.CustomerId)||null}}catch{return null}}
export async function authenticatePortal(email:string,password:string){const accounts=await getRows(SHEETS.commercePortalAccounts,true);const a=accounts.find(x=>String(x.Email||"").toLowerCase()===email.toLowerCase()&&bool(x.IsActive??true));if(!a||!await verifyPassword(password,a.PasswordHash))return null;return a}
export async function storefront(search="",category=""){const [products,books,categories,balances,warehouses]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.catalogueBooks),getRows(SHEETS.catalogueCategories),getRows(SHEETS.inventoryBalances),getRows(SHEETS.warehouses)]);const sellingWarehouses=new Set(warehouses.filter(w=>bool(w.IsActive)&&bool(w.AllowSales)).map(w=>w.Id));let rows=products.filter(p=>bool(p.IsActive??true)&&String(p.Status||"ACTIVE")!=="INACTIVE");if(search){const q=search.toLowerCase();rows=rows.filter(p=>String(p.Name||"").toLowerCase().includes(q)||String(p.Code||"").toLowerCase().includes(q)||String(p.Description||"").toLowerCase().includes(q))}if(category)rows=rows.filter(p=>p.CategoryId===category);return Promise.all(rows.map(async p=>{const stock=balances.filter(b=>b.ProductId===p.Id&&sellingWarehouses.has(b.WarehouseId)&&bool(b.IsActive??true)).reduce((s,b)=>s+Math.max(0,num(b.QuantityOnHand)-num(b.QuantityReserved)-num(b.QuantityDamaged)),0);const price=await resolvePrice(p.Id,"RETAIL",1);const book=books.find(b=>b.ProductId===p.Id);return {...p,Available:stock,OnlinePrice:price?.unitPrice??num(p.SellingPrice),CategoryName:categories.find(c=>c.Id===p.CategoryId)?.Name||"General",ISBN:book?.ISBN13||book?.ISBN10||""}}))}
export async function storefrontProduct(id:string){const rows=await storefront();return rows.find(x=>x.Id===id)||null}
export async function cartContext(){const c=await cookies();let cartId=c.get("risdel_cart")?.value;const carts=await getRows(SHEETS.commerceCarts,true);let cart=cartId?carts.find(x=>x.Id===cartId&&x.Status==="ACTIVE"&&bool(x.IsActive??true)):null;const lines=cart?(await getRows(SHEETS.commerceCartLines,true)).filter(l=>l.CartId===cart.Id&&bool(l.IsActive??true)):[];const products=await storefront();const mapped=lines.map(l=>{const p=products.find(x=>x.Id===l.ProductId);const q=num(l.Quantity);return {...l,Quantity:q,Product:p,LineTotal:q*num(l.UnitPrice)}}).filter(x=>x.Product);return {cart,lines:mapped,count:mapped.reduce((s,l)=>s+l.Quantity,0),subtotal:mapped.reduce((s,l)=>s+l.LineTotal,0)}}
export async function portalOrders(){const s=await portalSession();if(!s?.customer)return {session:s,orders:[]};const orders=await getRows(SHEETS.commerceOrders);return {session:s,orders:orders.filter(o=>o.CustomerId===s.customer.Id&&bool(o.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt)))}}
export async function commerceAdminSummary(){const [orders,payments,accounts]=await Promise.all([getRows(SHEETS.commerceOrders),getRows(SHEETS.commercePayments),getRows(SHEETS.commercePortalAccounts)]);const active=orders.filter(o=>bool(o.IsActive??true));return {orders:active,portalAccounts:accounts.filter(a=>bool(a.IsActive??true)).length,pending:active.filter(o=>["AWAITING_PAYMENT","CONFIRMED","PARTIAL","BACKORDER"].includes(String(o.Status))).length,revenue:active.filter(o=>["PAID","CONFIRMED","FULFILLED"].includes(String(o.Status))).reduce((s,o)=>s+num(o.Total),0),payments:payments.filter(p=>bool(p.IsActive??true))}}
