import {getRows,SHEETS} from "@/lib/sheets";
const n=(v:any)=>Number(v||0), active=(r:any)=>String(r.IsActive??true).toLowerCase()!=="false";
const date=(v:any)=>String(v||"").slice(0,10);
export async function accountingBase(){const [coa,journals,lines,periods,budgets,budgetLines,mappings,packs,packLines,cash,receivables,payables]=await Promise.all([getRows(SHEETS.financeChartOfAccounts),getRows(SHEETS.financeJournals),getRows(SHEETS.financeJournalLines),getRows(SHEETS.financePeriods),getRows(SHEETS.financeBudgets),getRows(SHEETS.financeBudgetLines),getRows(SHEETS.financeStatementMappings),getRows(SHEETS.financeManagementAccounts),getRows(SHEETS.financeManagementAccountLines),getRows(SHEETS.financeCashBankAccounts),getRows(SHEETS.financeReceivables),getRows(SHEETS.financePayables)]);return {coa:coa.filter(active),journals:journals.filter((j:any)=>active(j)&&j.Status==="POSTED"),lines:lines.filter(active),periods:periods.filter(active),budgets:budgets.filter(active),budgetLines:budgetLines.filter(active),mappings:mappings.filter(active),packs:packs.filter(active),packLines:packLines.filter(active),cash:cash.filter(active),receivables:receivables.filter(active),payables:payables.filter(active)}}
function inRange(v:any,start:string,end:string){const d=date(v);return d>=start&&d<=end}
export async function financialStatements(start:string,end:string,compareStart?:string,compareEnd?:string){const x=await accountingBase();const journalIds=new Set(x.journals.filter((j:any)=>inRange(j.JournalDate,start,end)).map((j:any)=>j.Id));const priorIds=new Set(x.journals.filter((j:any)=>compareStart&&compareEnd&&inRange(j.JournalDate,compareStart,compareEnd)).map((j:any)=>j.Id));const calc=(ids:Set<any>)=>x.coa.map((a:any)=>{const ls=x.lines.filter((l:any)=>l.AccountId===a.Id&&ids.has(l.JournalId));const debit=ls.reduce((s:number,l:any)=>s+n(l.Debit),0),credit=ls.reduce((s:number,l:any)=>s+n(l.Credit),0),type=String(a.AccountType||"").toUpperCase();const amount=["REVENUE","LIABILITY","EQUITY"].includes(type)?credit-debit:debit-credit;return {...a,Debit:debit,Credit:credit,Amount:amount}});const current=calc(journalIds),prior=calc(priorIds);const byType=(t:string)=>current.filter((a:any)=>String(a.AccountType).toUpperCase()===t).reduce((s:number,a:any)=>s+n(a.Amount),0);const priorType=(t:string)=>prior.filter((a:any)=>String(a.AccountType).toUpperCase()===t).reduce((s:number,a:any)=>s+n(a.Amount),0);const revenue=byType("REVENUE"),expenses=byType("EXPENSE"),cogs=current.filter((a:any)=>String(a.AccountCode)==="5000").reduce((s:number,a:any)=>s+n(a.Amount),0),opex=expenses-cogs;const assets=byType("ASSET"),liabilities=byType("LIABILITY"),equity=byType("EQUITY");const priorRevenue=priorType("REVENUE"),priorExpenses=priorType("EXPENSE"),priorCogs=prior.filter((a:any)=>String(a.AccountCode)==="5000").reduce((s:number,a:any)=>s+n(a.Amount),0);return {current,prior,revenue,cogs,grossProfit:revenue-cogs,operatingExpenses:opex,netProfit:revenue-expenses,assets,liabilities,equity,priorRevenue,priorCogs,priorGrossProfit:priorRevenue-priorCogs,priorOperatingExpenses:priorExpenses-priorCogs,priorNetProfit:priorRevenue-priorExpenses,start,end,compareStart,compareEnd}}
export async function budgetsWorkspace(){const x=await accountingBase();const enriched=x.budgets.map((b:any)=>{const ls=x.budgetLines.filter((l:any)=>l.BudgetId===b.Id);return {...b,Lines:ls,Total:ls.reduce((s:number,l:any)=>s+n(l.Amount),0)}});return {...x,budgets:enriched}}
export async function budgetVsActual(budgetId?:string){const x=await budgetsWorkspace();const budget=x.budgets.find((b:any)=>b.Id===budgetId)||x.budgets[0];if(!budget)return {...x,budget:null,rows:[],totalBudget:0,totalActual:0};const periods=new Map(x.periods.map((p:any)=>[p.PeriodCode,p]));const rows=budget.Lines.map((l:any)=>{const a=x.coa.find((a:any)=>a.Id===l.AccountId),p:any=periods.get(l.PeriodCode);let actual=0;if(a&&p){const jids=new Set(x.journals.filter((j:any)=>inRange(j.JournalDate,p.StartDate,p.EndDate)).map((j:any)=>j.Id));const ls=x.lines.filter((x:any)=>x.AccountId===a.Id&&jids.has(x.JournalId));const debit=ls.reduce((s:number,v:any)=>s+n(v.Debit),0),credit=ls.reduce((s:number,v:any)=>s+n(v.Credit),0),type=String(a.AccountType||"").toUpperCase();actual=["REVENUE","LIABILITY","EQUITY"].includes(type)?credit-debit:debit-credit}const amount=n(l.Amount),variance=actual-amount;return {...l,AccountCode:a?.AccountCode,AccountName:a?.AccountName,AccountType:a?.AccountType,Actual:actual,Variance:variance,VariancePercent:amount?variance/amount*100:0}});return {...x,budget,rows,totalBudget:rows.reduce((s:number,r:any)=>s+n(r.Amount),0),totalActual:rows.reduce((s:number,r:any)=>s+n(r.Actual),0)}}
export async function managementAccountsWorkspace(){const x=await accountingBase();return {...x,packs:x.packs.sort((a:any,b:any)=>String(b.GeneratedAt).localeCompare(String(a.GeneratedAt)))}}
