import { usingGoogleSheets } from "@/lib/data-provider";
import * as gs from "@/data/google-services";
import * as sqlData from "@/data/providers/sql-server/legacy/auth-data";
export const listRoles=()=>usingGoogleSheets()?gs.gsListRoles():sqlData.listRoles();
export const listUsers=()=>usingGoogleSheets()?gs.gsListUsers():sqlData.listUsers();
export const getRole=(id:string)=>usingGoogleSheets()?gs.gsGetRole(id):sqlData.getRole(id);
export const securitySummary=()=>usingGoogleSheets()?gs.gsSecuritySummary():sqlData.securitySummary();
export const loginHistory=()=>usingGoogleSheets()?gs.gsLoginHistory():sqlData.loginHistory();
export const activeSessions=()=>usingGoogleSheets()?gs.gsActiveSessions():sqlData.activeSessions();
export const getUser=(id:string)=>usingGoogleSheets()?gs.gsGetUser(id):sqlData.getUser(id);
