"use client";
import {useActionState} from "react";
import {createPurchaseRequest,createRequestFromReorder,submitPurchaseRequest,decidePurchaseRequest,createPurchaseOrder,markPurchaseOrderSent,cancelPurchaseOrder,type ProcurementActionState} from "@/app/actions/procurement";
function Msg({state}:{state:ProcurementActionState}){return <>{state.error&&<p className="form-error">{state.error}</p>}{state.success&&<p className="form-success">{state.success}</p>}</>}
export function PurchaseRequestForm({products,warehouses,suppliers}:{products:any[];warehouses:any[];suppliers:any[]}){const [state,action]=useActionState(createPurchaseRequest,{});return <form action={action} className="form-grid"><label>Product<select className="input" name="productId" required><option value="">Select product…</option>{products.map(p=><option key={p.Id} value={p.Id}>{p.Code} — {p.Name}</option>)}</select></label><label>Warehouse<select className="input" name="warehouseId" required><option value="">Select warehouse…</option>{warehouses.map(w=><option key={w.Id} value={w.Id}>{w.Name}</option>)}</select></label><label>Quantity<input className="input" type="number" min="1" name="quantity" required/></label><label>Priority<select className="input" name="priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label>Preferred supplier<select className="input" name="supplierId"><option value="">Unassigned</option>{suppliers.map(s=><option key={s.Id} value={s.Id}>{s.Name}</option>)}</select></label><label>Estimated unit cost<input className="input" type="number" min="0" step="0.01" name="estimatedUnitCost"/></label><label className="span-2">Reason<input className="input" name="reason" placeholder="Stock replenishment, school order, special order…"/></label><label className="span-2">Notes<textarea className="input" name="notes" rows={2}/></label><div className="span-2"><Msg state={state}/><button className="btn btn-primary">Create request</button></div></form>}
export function ReorderRequestButton({productId,warehouseId}:{productId:string;warehouseId:string}){const [state,action]=useActionState(createRequestFromReorder,{});return <form action={action}><input type="hidden" name="productId" value={productId}/><input type="hidden" name="warehouseId" value={warehouseId}/><button className="btn btn-secondary">Create & submit</button><Msg state={state}/></form>}
export function SubmitRequestButton({id}:{id:string}){const [state,action]=useActionState(submitPurchaseRequest,{});return <form action={action}><input type="hidden" name="id" value={id}/><button className="btn btn-primary">Submit for approval</button><Msg state={state}/></form>}
export function RequestDecisionForm({id}:{id:string}){const [state,action]=useActionState(decidePurchaseRequest,{});return <form action={action} className="procurement-decision"><input type="hidden" name="id" value={id}/><button className="btn btn-primary" name="decision" value="APPROVE">Approve</button><input className="input" name="rejectionReason" placeholder="Reason if rejecting"/><button className="btn btn-secondary" name="decision" value="REJECT">Reject</button><Msg state={state}/></form>}
export function CreatePOForm({requestId,suppliers}:{requestId:string;suppliers:any[]}){const [state,action]=useActionState(createPurchaseOrder,{});return <form action={action} className="form-grid"><input type="hidden" name="requestId" value={requestId}/><label>Supplier<select className="input" name="supplierId" required><option value="">Select supplier…</option>{suppliers.map(s=><option key={s.Id} value={s.Id}>{s.Name}{String(s.Preferred).toLowerCase()==="true"?" • Preferred":""}</option>)}</select></label><label>Expected delivery<input className="input" name="expectedDeliveryDate" type="date"/></label><label>Tax amount<input className="input" name="taxAmount" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Notes<input className="input" name="notes"/></label><div className="span-2"><Msg state={state}/><button className="btn btn-primary">Create purchase order</button></div></form>}
export function POActions({id,status}:{id:string;status:string}){const [sent,sentAction]=useActionState(markPurchaseOrderSent,{});const [cancel,cancelAction]=useActionState(cancelPurchaseOrder,{});return <div className="procurement-action-stack">{status==="APPROVED"&&<form action={sentAction}><input type="hidden" name="id" value={id}/><button className="btn btn-primary">Mark sent to supplier</button><Msg state={sent}/></form>}{!["CANCELLED","CLOSED"].includes(status)&&<form action={cancelAction}><input type="hidden" name="id" value={id}/><input className="input" name="reason" placeholder="Cancellation reason"/><button className="btn btn-secondary">Cancel PO</button><Msg state={cancel}/></form>}</div>}
