import { getRows,SHEETS } from "@/lib/sheets";
const bool=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1";
const num=(v:any)=>v==null||v===""?0:Number(v);
export const salesMoney=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(n||0);
export async function posContext(userId:string,heldId?:string){
 const [products,books,barcodes,balances,warehouses,branches,customers,methods,shifts,held,heldLines]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.catalogueBooks),getRows(SHEETS.catalogueBarcodes),getRows(SHEETS.inventoryBalances),getRows(SHEETS.warehouses),getRows(SHEETS.branches),getRows(SHEETS.salesCustomers),getRows(SHEETS.paymentMethods),getRows(SHEETS.salesShifts),getRows(SHEETS.salesHeld),getRows(SHEETS.salesHeldLines)]);
 const activeWarehouses=warehouses.filter(w=>bool(w.IsActive)&&bool(w.AllowSales)).map(w=>({...w,BranchName:branches.find(b=>b.Id===w.BranchId)?.Name||""}));
 const inventory=balances.filter(b=>bool(b.IsActive??true)).map(b=>{const p=products.find(x=>x.Id===b.ProductId),book=books.find(x=>x.ProductId===b.ProductId),barcode=barcodes.find(x=>x.ProductId===b.ProductId&&bool(x.IsPrimary??true));const on=num(b.QuantityOnHand),reserved=num(b.QuantityReserved);return {ProductId:b.ProductId,WarehouseId:b.WarehouseId,Code:p?.Code||"",Name:p?.Name||"Unknown",ProductType:p?.ProductType||"",SellingPrice:num(p?.SellingPrice),CostPrice:num(b.AverageCost||p?.CostPrice),ISBN:book?.ISBN13||book?.ISBN10||"",Barcode:barcode?.Barcode||"",Available:Math.max(0,on-reserved),TrackInventory:bool(p?.TrackInventory??true),IsActive:bool(p?.IsActive)}}).filter(x=>x.IsActive&&x.Available>0);
 const openShift=shifts.find(s=>s.UserId===userId&&s.Status==="OPEN"&&bool(s.IsActive??true))||null;
 const heldSale=heldId?held.find(h=>h.Id===heldId&&h.Status==="HELD"&&bool(h.IsActive??true)):null;const initialCart=heldSale?heldLines.filter(l=>l.HeldSaleId===heldSale.Id&&bool(l.IsActive??true)).map(l=>{const item=inventory.find(i=>i.ProductId===l.ProductId&&i.WarehouseId===heldSale.WarehouseId);return item?{productId:item.ProductId,warehouseId:item.WarehouseId,name:item.Name,code:item.Code,quantity:num(l.Quantity),unitPrice:num(l.UnitPrice),discountAmount:num(l.DiscountAmount),available:item.Available}:null}).filter(Boolean):[];return {inventory,warehouses:activeWarehouses,customers:customers.filter(c=>bool(c.IsActive??true)).sort((a,b)=>String(a.Name).localeCompare(String(b.Name))),paymentMethods:methods.filter(m=>bool(m.IsActive??true)).sort((a,b)=>num(a.SortOrder)-num(b.SortOrder)),openShift,heldSale,initialCart};
}
export async function salesSummary(){const rows=await getRows(SHEETS.salesTransactions);const today=new Date().toISOString().slice(0,10),month=today.slice(0,7);const completed=rows.filter(r=>r.Status==="COMPLETED"&&bool(r.IsActive??true));const t=completed.filter(r=>String(r.CompletedAt||r.CreatedAt).slice(0,10)===today),m=completed.filter(r=>String(r.CompletedAt||r.CreatedAt).slice(0,7)===month);return {todayRevenue:t.reduce((s,r)=>s+num(r.Total),0),todayTransactions:t.length,monthRevenue:m.reduce((s,r)=>s+num(r.Total),0),monthGrossProfit:m.reduce((s,r)=>s+num(r.GrossProfit),0)}}
export async function recentSales(limit=100){const [sales,customers,users]=await Promise.all([getRows(SHEETS.salesTransactions),getRows(SHEETS.salesCustomers),getRows(SHEETS.users)]);return sales.filter(r=>bool(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).slice(0,limit).map(r=>({...r,Subtotal:num(r.Subtotal),DiscountTotal:num(r.DiscountTotal),Total:num(r.Total),GrossProfit:num(r.GrossProfit),CustomerName:customers.find(c=>c.Id===r.CustomerId)?.Name||r.CustomerName||"Walk-in Customer",CashierName:users.find(u=>u.Id===r.CashierId)?.DisplayName||"Unknown"}))}
export async function heldSales(){const [held,customers,users]=await Promise.all([getRows(SHEETS.salesHeld),getRows(SHEETS.salesCustomers),getRows(SHEETS.users)]);return held.filter(r=>r.Status==="HELD"&&bool(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>({...r,Total:num(r.Total),CustomerName:customers.find(c=>c.Id===r.CustomerId)?.Name||r.CustomerName||"Walk-in Customer",CashierName:users.find(u=>u.Id===r.CreatedBy)?.DisplayName||""}))}
export async function salesShifts(){const [shifts,users,warehouses]=await Promise.all([getRows(SHEETS.salesShifts),getRows(SHEETS.users),getRows(SHEETS.warehouses)]);return shifts.filter(r=>bool(r.IsActive??true)).sort((a,b)=>String(b.OpenedAt).localeCompare(String(a.OpenedAt))).map(r=>({...r,OpeningCash:num(r.OpeningCash),ExpectedCash:num(r.ExpectedCash),ClosingCash:num(r.ClosingCash),Variance:num(r.Variance),CashierName:users.find(u=>u.Id===r.UserId)?.DisplayName||"Unknown",WarehouseName:warehouses.find(w=>w.Id===r.WarehouseId)?.Name||"Unknown"}))}
export async function receiptData(id:string){const [sales,lines,payments,products,customers,users,companies,branches,warehouses]=await Promise.all([getRows(SHEETS.salesTransactions),getRows(SHEETS.salesLines),getRows(SHEETS.salesPayments),getRows(SHEETS.catalogueProducts),getRows(SHEETS.salesCustomers),getRows(SHEETS.users),getRows(SHEETS.companies),getRows(SHEETS.branches),getRows(SHEETS.warehouses)]);const sale=sales.find(s=>s.Id===id);if(!sale)return null;return {sale:{...sale,Subtotal:num(sale.Subtotal),DiscountTotal:num(sale.DiscountTotal),Total:num(sale.Total),AmountPaid:num(sale.AmountPaid),ChangeDue:num(sale.ChangeDue)},lines:lines.filter(l=>l.SaleId===id&&bool(l.IsActive??true)).map(l=>({...l,Quantity:num(l.Quantity),UnitPrice:num(l.UnitPrice),DiscountAmount:num(l.DiscountAmount),LineTotal:num(l.LineTotal),ProductName:products.find(p=>p.Id===l.ProductId)?.Name||l.ProductName||"Product"})),payments:payments.filter(p=>p.SaleId===id&&bool(p.IsActive??true)).map(p=>({...p,Amount:num(p.Amount)})),customer:customers.find(c=>c.Id===sale.CustomerId)||null,cashier:users.find(u=>u.Id===sale.CashierId)||null,company:companies.find(c=>bool(c.IsActive))||null,branch:branches.find(b=>b.Id===sale.BranchId)||null,warehouse:warehouses.find(w=>w.Id===sale.WarehouseId)||null};}
