import { getRows,SHEETS } from "@/lib/sheets";
const bool=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1";
const num=(v:any)=>v==null||v===""?0:Number(v);
export const money=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(n||0);
export async function salesDocumentLookups(){
 const [products,books,barcodes,customers,warehouses,branches,paymentMethods]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.catalogueBooks),getRows(SHEETS.catalogueBarcodes),getRows(SHEETS.salesCustomers),getRows(SHEETS.warehouses),getRows(SHEETS.branches),getRows(SHEETS.paymentMethods)]);
 return {products:products.filter(p=>bool(p.IsActive)).map(p=>({...p,SellingPrice:num(p.SellingPrice),ISBN:books.find(b=>b.ProductId===p.Id)?.ISBN13||books.find(b=>b.ProductId===p.Id)?.ISBN10||"",Barcode:barcodes.find(b=>b.ProductId===p.Id&&bool(b.IsPrimary??true))?.Barcode||""})).sort((a,b)=>String(a.Name).localeCompare(String(b.Name))),customers:customers.filter(c=>bool(c.IsActive??true)).sort((a,b)=>String(a.Name).localeCompare(String(b.Name))),warehouses:warehouses.filter(w=>bool(w.IsActive)&&bool(w.AllowSales)).map(w=>({...w,BranchName:branches.find(b=>b.Id===w.BranchId)?.Name||""})),paymentMethods:paymentMethods.filter(m=>bool(m.IsActive??true)).sort((a,b)=>num(a.SortOrder)-num(b.SortOrder))};
}
export async function listQuotations(){const [rows,customers,users]=await Promise.all([getRows(SHEETS.salesQuotations),getRows(SHEETS.salesCustomers),getRows(SHEETS.users)]);return rows.filter(r=>bool(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>({...r,Subtotal:num(r.Subtotal),DiscountTotal:num(r.DiscountTotal),TaxTotal:num(r.TaxTotal),Total:num(r.Total),CustomerName:customers.find(c=>c.Id===r.CustomerId)?.Name||r.CustomerName||"Walk-in Customer",CreatedByName:users.find(u=>u.Id===r.CreatedBy)?.DisplayName||""}))}
export async function listSalesOrders(){const [rows,customers,warehouses]=await Promise.all([getRows(SHEETS.salesOrders),getRows(SHEETS.salesCustomers),getRows(SHEETS.warehouses)]);return rows.filter(r=>bool(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>({...r,Subtotal:num(r.Subtotal),DiscountTotal:num(r.DiscountTotal),TaxTotal:num(r.TaxTotal),Total:num(r.Total),AmountInvoiced:num(r.AmountInvoiced),CustomerName:customers.find(c=>c.Id===r.CustomerId)?.Name||r.CustomerName||"Walk-in Customer",WarehouseName:warehouses.find(w=>w.Id===r.WarehouseId)?.Name||""}))}
export async function listInvoices(){const [rows,customers]=await Promise.all([getRows(SHEETS.salesInvoices),getRows(SHEETS.salesCustomers)]);return rows.filter(r=>bool(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>({...r,Subtotal:num(r.Subtotal),DiscountTotal:num(r.DiscountTotal),TaxTotal:num(r.TaxTotal),Total:num(r.Total),AmountPaid:num(r.AmountPaid),BalanceDue:num(r.BalanceDue),CustomerName:customers.find(c=>c.Id===r.CustomerId)?.Name||r.CustomerName||"Walk-in Customer"}))}
export async function getQuotation(id:string){const [rows,lines,products,customers]=await Promise.all([getRows(SHEETS.salesQuotations),getRows(SHEETS.salesQuotationLines),getRows(SHEETS.catalogueProducts),getRows(SHEETS.salesCustomers)]);const doc=rows.find(r=>r.Id===id&&bool(r.IsActive??true));if(!doc)return null;return {doc:{...doc,Subtotal:num(doc.Subtotal),DiscountTotal:num(doc.DiscountTotal),TaxTotal:num(doc.TaxTotal),Total:num(doc.Total)},customer:customers.find(c=>c.Id===doc.CustomerId)||null,lines:lines.filter(l=>l.QuotationId===id&&bool(l.IsActive??true)).map(l=>({...l,Quantity:num(l.Quantity),UnitPrice:num(l.UnitPrice),DiscountAmount:num(l.DiscountAmount),TaxAmount:num(l.TaxAmount),LineTotal:num(l.LineTotal),ProductName:products.find(p=>p.Id===l.ProductId)?.Name||l.ProductName||"Product"}))}}
export async function getSalesOrder(id:string){const [rows,lines,products,customers,warehouses]=await Promise.all([getRows(SHEETS.salesOrders),getRows(SHEETS.salesOrderLines),getRows(SHEETS.catalogueProducts),getRows(SHEETS.salesCustomers),getRows(SHEETS.warehouses)]);const doc=rows.find(r=>r.Id===id&&bool(r.IsActive??true));if(!doc)return null;return {doc:{...doc,Subtotal:num(doc.Subtotal),DiscountTotal:num(doc.DiscountTotal),TaxTotal:num(doc.TaxTotal),Total:num(doc.Total),AmountInvoiced:num(doc.AmountInvoiced)},customer:customers.find(c=>c.Id===doc.CustomerId)||null,warehouse:warehouses.find(w=>w.Id===doc.WarehouseId)||null,lines:lines.filter(l=>l.OrderId===id&&bool(l.IsActive??true)).map(l=>({...l,Quantity:num(l.Quantity),QuantityReserved:num(l.QuantityReserved),QuantityFulfilled:num(l.QuantityFulfilled),QuantityBackordered:num(l.QuantityBackordered),UnitPrice:num(l.UnitPrice),DiscountAmount:num(l.DiscountAmount),TaxAmount:num(l.TaxAmount),LineTotal:num(l.LineTotal),ProductName:products.find(p=>p.Id===l.ProductId)?.Name||l.ProductName||"Product"}))}}
export async function getInvoice(id:string){const [rows,lines,payments,products,customers,orders,companies,branches]=await Promise.all([getRows(SHEETS.salesInvoices),getRows(SHEETS.salesInvoiceLines),getRows(SHEETS.salesInvoicePayments),getRows(SHEETS.catalogueProducts),getRows(SHEETS.salesCustomers),getRows(SHEETS.salesOrders),getRows(SHEETS.companies),getRows(SHEETS.branches)]);const doc=rows.find(r=>r.Id===id&&bool(r.IsActive??true));if(!doc)return null;return {doc:{...doc,Subtotal:num(doc.Subtotal),DiscountTotal:num(doc.DiscountTotal),TaxTotal:num(doc.TaxTotal),Total:num(doc.Total),AmountPaid:num(doc.AmountPaid),BalanceDue:num(doc.BalanceDue)},customer:customers.find(c=>c.Id===doc.CustomerId)||null,order:orders.find(o=>o.Id===doc.OrderId)||null,company:companies.find(c=>bool(c.IsActive))||null,branch:branches.find(b=>b.Id===doc.BranchId)||null,lines:lines.filter(l=>l.InvoiceId===id&&bool(l.IsActive??true)).map(l=>({...l,Quantity:num(l.Quantity),UnitPrice:num(l.UnitPrice),DiscountAmount:num(l.DiscountAmount),TaxAmount:num(l.TaxAmount),LineTotal:num(l.LineTotal),ProductName:products.find(p=>p.Id===l.ProductId)?.Name||l.ProductName||"Product"})),payments:payments.filter(p=>p.InvoiceId===id&&bool(p.IsActive??true)).map(p=>({...p,Amount:num(p.Amount)}))}}
export async function salesDocumentsSummary(){const [q,o,i]=await Promise.all([listQuotations(),listSalesOrders(),listInvoices()]);return {openQuotes:q.filter(x=>["DRAFT","SENT"].includes(String(x.Status))).length,openQuoteValue:q.filter(x=>["DRAFT","SENT"].includes(String(x.Status))).reduce((s,x)=>s+x.Total,0),openOrders:o.filter(x=>!["FULFILLED","CANCELLED"].includes(String(x.Status))).length,backorders:o.filter(x=>x.Status==="BACKORDER"||x.Status==="PARTIAL").length,invoiceBalance:i.filter(x=>num(x.BalanceDue)>0).reduce((s,x)=>s+x.BalanceDue,0),overdueInvoices:i.filter(x=>x.DueDate&&String(x.DueDate)<new Date().toISOString().slice(0,10)&&num(x.BalanceDue)>0).length}}
