/* Risdel Books Module 06 — Inventory Management (future SQL Server migration reference) */
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='inventory') EXEC('CREATE SCHEMA inventory');
GO
CREATE TABLE inventory.StockBalances (Id uniqueidentifier NOT NULL PRIMARY KEY, ProductId uniqueidentifier NOT NULL, WarehouseId uniqueidentifier NOT NULL, QuantityOnHand decimal(18,3) NOT NULL DEFAULT 0, QuantityReserved decimal(18,3) NOT NULL DEFAULT 0, QuantityDamaged decimal(18,3) NOT NULL DEFAULT 0, AverageCost decimal(18,4) NOT NULL DEFAULT 0, LastMovementAt datetime2 NULL, CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(), CreatedBy uniqueidentifier NULL, UpdatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(), UpdatedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1, CONSTRAINT UQ_InventoryBalance UNIQUE(ProductId,WarehouseId));
CREATE TABLE inventory.StockMovements (Id uniqueidentifier NOT NULL PRIMARY KEY, ProductId uniqueidentifier NOT NULL, WarehouseId uniqueidentifier NOT NULL, MovementType nvarchar(40) NOT NULL, Quantity decimal(18,3) NOT NULL, ReservedDelta decimal(18,3) NOT NULL DEFAULT 0, DamagedDelta decimal(18,3) NOT NULL DEFAULT 0, UnitCost decimal(18,4) NOT NULL DEFAULT 0, ReferenceType nvarchar(40) NULL, ReferenceId uniqueidentifier NULL, Reason nvarchar(500) NULL, BalanceAfter decimal(18,3) NOT NULL, OccurredAt datetime2 NOT NULL DEFAULT sysutcdatetime(), CreatedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE inventory.Transfers (Id uniqueidentifier NOT NULL PRIMARY KEY, TransferNumber nvarchar(30) NOT NULL UNIQUE, SourceWarehouseId uniqueidentifier NOT NULL, DestinationWarehouseId uniqueidentifier NOT NULL, Status nvarchar(30) NOT NULL, Notes nvarchar(500) NULL, RequestedAt datetime2 NULL, DispatchedAt datetime2 NULL, ReceivedAt datetime2 NULL, CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(), CreatedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE inventory.TransferLines (Id uniqueidentifier NOT NULL PRIMARY KEY, TransferId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, QuantityRequested decimal(18,3) NOT NULL, QuantityDispatched decimal(18,3) NOT NULL DEFAULT 0, QuantityReceived decimal(18,3) NOT NULL DEFAULT 0, UnitCost decimal(18,4) NOT NULL DEFAULT 0, CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(), IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE inventory.Adjustments (Id uniqueidentifier NOT NULL PRIMARY KEY, ProductId uniqueidentifier NOT NULL, WarehouseId uniqueidentifier NOT NULL, AdjustmentType nvarchar(30) NOT NULL, Quantity decimal(18,3) NOT NULL, Reason nvarchar(500) NOT NULL, Reference nvarchar(100) NULL, Status nvarchar(30) NOT NULL, CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(), CreatedBy uniqueidentifier NULL, ApprovedAt datetime2 NULL, ApprovedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE inventory.DamagedStock (Id uniqueidentifier NOT NULL PRIMARY KEY, ProductId uniqueidentifier NOT NULL, WarehouseId uniqueidentifier NOT NULL, Quantity decimal(18,3) NOT NULL, Reason nvarchar(500) NOT NULL, Condition nvarchar(40) NULL, Disposition nvarchar(40) NULL, Notes nvarchar(500) NULL, CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(), CreatedBy uniqueidentifier NULL, ResolvedAt datetime2 NULL, ResolvedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE inventory.Reservations (Id uniqueidentifier NOT NULL PRIMARY KEY, ProductId uniqueidentifier NOT NULL, WarehouseId uniqueidentifier NOT NULL, Quantity decimal(18,3) NOT NULL, ReferenceType nvarchar(40) NULL, ReferenceId nvarchar(100) NULL, CustomerReference nvarchar(200) NULL, Status nvarchar(30) NOT NULL, ExpiresAt datetime2 NULL, CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(), CreatedBy uniqueidentifier NULL, ReleasedAt datetime2 NULL, ReleasedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
GO
