/* Risdel Books Module 11 - future relational migration reference. Google Sheets GS-009 is active now. */
IF SCHEMA_ID('sales') IS NULL EXEC('CREATE SCHEMA sales');
GO
CREATE TABLE sales.Reservations (Id uniqueidentifier NOT NULL PRIMARY KEY, ReservationNumber nvarchar(30) NOT NULL UNIQUE, CustomerId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, WarehouseId uniqueidentifier NOT NULL, Quantity decimal(18,3) NOT NULL, Status nvarchar(30) NOT NULL, DepositAmount decimal(18,2) NOT NULL DEFAULT 0, ExpiresAt datetime2 NULL, Notes nvarchar(1000) NULL, ReadyAt datetime2 NULL, CollectedAt datetime2 NULL, ReleasedAt datetime2 NULL, SalesTransactionId uniqueidentifier NULL, CreatedAt datetime2 NOT NULL, CreatedBy uniqueidentifier NULL, UpdatedAt datetime2 NOT NULL, UpdatedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
GO
CREATE TABLE sales.SpecialOrders (Id uniqueidentifier NOT NULL PRIMARY KEY, SpecialOrderNumber nvarchar(30) NOT NULL UNIQUE, CustomerId uniqueidentifier NOT NULL, ProductId uniqueidentifier NULL, RequestedTitle nvarchar(300) NULL, RequestedISBN nvarchar(30) NULL, RequestedAuthor nvarchar(200) NULL, Quantity decimal(18,3) NOT NULL, EstimatedUnitPrice decimal(18,2) NOT NULL DEFAULT 0, EstimatedTotal decimal(18,2) NOT NULL DEFAULT 0, DepositAmount decimal(18,2) NOT NULL DEFAULT 0, BalanceDue decimal(18,2) NOT NULL DEFAULT 0, Status nvarchar(30) NOT NULL, SupplierName nvarchar(200) NULL, SupplierReference nvarchar(100) NULL, ExpectedArrivalDate date NULL, ActualArrivalDate date NULL, NotificationStatus nvarchar(30) NULL, SalesOrderId uniqueidentifier NULL, Notes nvarchar(1000) NULL, CreatedAt datetime2 NOT NULL, CreatedBy uniqueidentifier NULL, UpdatedAt datetime2 NOT NULL, UpdatedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
GO
CREATE TABLE sales.Deposits (Id uniqueidentifier NOT NULL PRIMARY KEY, DepositNumber nvarchar(30) NOT NULL UNIQUE, ReferenceType nvarchar(30) NOT NULL, ReferenceId uniqueidentifier NOT NULL, CustomerId uniqueidentifier NOT NULL, Amount decimal(18,2) NOT NULL, PaymentMethod nvarchar(30) NOT NULL, PaymentReference nvarchar(100) NULL, Status nvarchar(30) NOT NULL, ReceivedAt datetime2 NOT NULL, CreatedAt datetime2 NOT NULL, CreatedBy uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
GO
