/* Risdel Books Module 25 — Approval Workflow Engine
   Future relational migration reference. Google Sheets remains the active provider. */
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='workflow') EXEC('CREATE SCHEMA workflow');
GO
CREATE TABLE workflow.ApprovalDefinitions(Id uniqueidentifier NOT NULL PRIMARY KEY,Code nvarchar(80) NOT NULL UNIQUE,Name nvarchar(160) NOT NULL,Module nvarchar(80) NOT NULL,SourceType nvarchar(80) NOT NULL,Description nvarchar(500) NULL,TriggerStatus nvarchar(250) NULL,AmountField nvarchar(80) NULL,BranchScoped bit NOT NULL DEFAULT 0,AllowSelfApproval bit NOT NULL DEFAULT 0,EscalationHours int NULL,Status nvarchar(30) NOT NULL,CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(),CreatedBy uniqueidentifier NULL,UpdatedAt datetime2 NULL,UpdatedBy uniqueidentifier NULL,IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE workflow.ApprovalDefinitionSteps(Id uniqueidentifier NOT NULL PRIMARY KEY,DefinitionId uniqueidentifier NOT NULL,StepNumber int NOT NULL,StepName nvarchar(160) NOT NULL,ApproverRoleCode nvarchar(80) NULL,ApproverPermission nvarchar(160) NULL,MinAmount decimal(19,4) NULL,MaxAmount decimal(19,4) NULL,SLAHours int NULL,EscalationPermission nvarchar(160) NULL,IsRequired bit NOT NULL DEFAULT 1,CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(),CreatedBy uniqueidentifier NULL,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT FK_ApprovalDefinitionSteps_Definition FOREIGN KEY(DefinitionId) REFERENCES workflow.ApprovalDefinitions(Id));
CREATE TABLE workflow.ApprovalRequests(Id uniqueidentifier NOT NULL PRIMARY KEY,RequestNumber nvarchar(50) NOT NULL UNIQUE,DefinitionId uniqueidentifier NOT NULL,SourceType nvarchar(80) NOT NULL,SourceId uniqueidentifier NOT NULL,SourceNumber nvarchar(100) NULL,Title nvarchar(250) NOT NULL,Amount decimal(19,4) NULL,BranchId uniqueidentifier NULL,RequestedBy uniqueidentifier NULL,RequestedAt datetime2 NOT NULL,Status nvarchar(30) NOT NULL,CurrentStep int NOT NULL DEFAULT 1,Priority nvarchar(30) NULL,DueAt datetime2 NULL,CompletedAt datetime2 NULL,CompletedBy uniqueidentifier NULL,LastDecision nvarchar(30) NULL,LastComment nvarchar(1000) NULL,CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(),UpdatedAt datetime2 NULL,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT FK_ApprovalRequests_Definition FOREIGN KEY(DefinitionId) REFERENCES workflow.ApprovalDefinitions(Id));
CREATE UNIQUE INDEX UX_ApprovalRequests_ActiveSource ON workflow.ApprovalRequests(SourceType,SourceId,IsActive);
CREATE TABLE workflow.ApprovalSteps(Id uniqueidentifier NOT NULL PRIMARY KEY,ApprovalRequestId uniqueidentifier NOT NULL,DefinitionStepId uniqueidentifier NULL,StepNumber int NOT NULL,StepName nvarchar(160) NOT NULL,ApproverRoleCode nvarchar(80) NULL,ApproverPermission nvarchar(160) NULL,AssignedTo uniqueidentifier NULL,Status nvarchar(30) NOT NULL,DueAt datetime2 NULL,Decision nvarchar(30) NULL,DecisionAt datetime2 NULL,DecisionBy uniqueidentifier NULL,Comment nvarchar(1000) NULL,CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(),UpdatedAt datetime2 NULL,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT FK_ApprovalSteps_Request FOREIGN KEY(ApprovalRequestId) REFERENCES workflow.ApprovalRequests(Id));
CREATE TABLE workflow.ApprovalEvents(Id uniqueidentifier NOT NULL PRIMARY KEY,ApprovalRequestId uniqueidentifier NOT NULL,EventType nvarchar(50) NOT NULL,Description nvarchar(1000) NULL,ActorId uniqueidentifier NULL,OccurredAt datetime2 NOT NULL DEFAULT sysutcdatetime(),Metadata nvarchar(max) NULL,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT FK_ApprovalEvents_Request FOREIGN KEY(ApprovalRequestId) REFERENCES workflow.ApprovalRequests(Id));
CREATE TABLE workflow.ApprovalDelegations(Id uniqueidentifier NOT NULL PRIMARY KEY,DelegatorUserId uniqueidentifier NOT NULL,DelegateUserId uniqueidentifier NOT NULL,PermissionScope nvarchar(160) NOT NULL,StartAt datetime2 NOT NULL,EndAt datetime2 NOT NULL,Reason nvarchar(500) NULL,Status nvarchar(30) NOT NULL,CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(),CreatedBy uniqueidentifier NULL,IsActive bit NOT NULL DEFAULT 1);
GO
