/* Risdel Books Module 34 — Fixed Assets & Depreciation
   Future relational-provider migration reference. Google Sheets remains the active provider. */
CREATE SCHEMA fixedassets;
GO
CREATE TABLE fixedassets.AssetClasses (Id uniqueidentifier NOT NULL PRIMARY KEY, Code nvarchar(30) NOT NULL UNIQUE, Name nvarchar(150) NOT NULL, UsefulLifeMonths int NOT NULL, DepreciationMethod nvarchar(30) NOT NULL, ResidualValuePercent decimal(9,4) NOT NULL DEFAULT 0, AnnualRate decimal(9,4) NOT NULL DEFAULT 0, AssetAccountId uniqueidentifier NULL, AccumDepAccountId uniqueidentifier NULL, DepExpenseAccountId uniqueidentifier NULL, ImpairmentExpenseAccountId uniqueidentifier NULL, IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE fixedassets.Assets (Id uniqueidentifier NOT NULL PRIMARY KEY, AssetNumber nvarchar(40) NOT NULL UNIQUE, AssetName nvarchar(200) NOT NULL, ClassId uniqueidentifier NOT NULL, AcquisitionDate date NOT NULL, AcquisitionCost decimal(19,4) NOT NULL, CapitalizedCost decimal(19,4) NOT NULL DEFAULT 0, ResidualValue decimal(19,4) NOT NULL DEFAULT 0, DepreciationStartDate date NULL, UsefulLifeMonths int NULL, DepreciationMethod nvarchar(30) NULL, AnnualRate decimal(9,4) NULL, BranchId uniqueidentifier NULL, WarehouseId uniqueidentifier NULL, Custodian nvarchar(200) NULL, Status nvarchar(30) NOT NULL, IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE fixedassets.DepreciationRuns (Id uniqueidentifier NOT NULL PRIMARY KEY, RunNumber nvarchar(40) NOT NULL UNIQUE, PeriodId uniqueidentifier NOT NULL, RunDate date NOT NULL, Status nvarchar(30) NOT NULL, TotalDepreciation decimal(19,4) NOT NULL, AssetCount int NOT NULL, JournalId uniqueidentifier NULL);
CREATE TABLE fixedassets.DepreciationLines (Id uniqueidentifier NOT NULL PRIMARY KEY, RunId uniqueidentifier NOT NULL, PeriodId uniqueidentifier NOT NULL, AssetId uniqueidentifier NOT NULL, OpeningAccumulatedDepreciation decimal(19,4) NOT NULL, DepreciationAmount decimal(19,4) NOT NULL, ClosingAccumulatedDepreciation decimal(19,4) NOT NULL, Status nvarchar(30) NOT NULL);
CREATE TABLE fixedassets.Transfers (Id uniqueidentifier NOT NULL PRIMARY KEY, AssetId uniqueidentifier NOT NULL, TransferDate date NOT NULL, FromBranchId uniqueidentifier NULL, ToBranchId uniqueidentifier NULL, Reason nvarchar(500) NULL, Status nvarchar(30) NOT NULL);
CREATE TABLE fixedassets.Disposals (Id uniqueidentifier NOT NULL PRIMARY KEY, AssetId uniqueidentifier NOT NULL, DisposalDate date NOT NULL, Proceeds decimal(19,4) NOT NULL, CarryingAmount decimal(19,4) NOT NULL, GainLoss decimal(19,4) NOT NULL, Status nvarchar(30) NOT NULL, JournalId uniqueidentifier NULL);
CREATE TABLE fixedassets.Impairments (Id uniqueidentifier NOT NULL PRIMARY KEY, AssetId uniqueidentifier NOT NULL, ImpairmentDate date NOT NULL, Amount decimal(19,4) NOT NULL, Reason nvarchar(500) NULL, Status nvarchar(30) NOT NULL, JournalId uniqueidentifier NULL);
GO
