"use server";
import {revalidatePath} from "next/cache";
import {appendRow,findById,getRows,newId,SHEETS} from "@/lib/sheets";
import {requirePermission} from "@/lib/authz";
import {writeAudit} from "@/lib/audit";
const n=(v:any)=>Number(v||0),yes=(v:any)=>String(v??true).toLowerCase()!=="false",now=()=>new Date().toISOString();
async function journalNo(){const rows=await getRows(SHEETS.financeJournals,true),y=new Date().getFullYear();let m=0;for(const r of rows)m=Math.max(m,Number(String(r.JournalNumber||"").split("-").pop())||0);return `JRN-${y}-${String(m+1).padStart(6,"0")}`}
async function account(code:string){const a=(await getRows(SHEETS.financeChartOfAccounts,true)).find((x:any)=>x.AccountCode===code&&yes(x.IsActive));if(!a)throw new Error(`Ledger account ${code} is not configured.`);return a}
async function already(type:string,id:string){return (await getRows(SHEETS.financeJournals,true)).some((j:any)=>j.ReferenceType===type&&j.ReferenceId===id&&j.Status==="POSTED"&&yes(j.IsActive))}
async function postJournal(actor:string,input:{date:string,type:string,refType:string,refId:string,description:string,branchId?:string,customerId?:string,supplierId?:string,lines:{code:string,debit?:number,credit?:number,description?:string}[]}){const periods=await getRows(SHEETS.financePeriods,true);const period=periods.find((p:any)=>yes(p.IsActive)&&String(input.date)>=String(p.StartDate)&&String(input.date)<=String(p.EndDate));if(period&&String(period.Status).toUpperCase()==="CLOSED")throw new Error(`Accounting period ${period.Name||period.PeriodCode} is closed. Reopen it before posting dated ${input.date}.`);if(await already(input.refType,input.refId))return false;const totalD=input.lines.reduce((a,l)=>a+n(l.debit),0),totalC=input.lines.reduce((a,l)=>a+n(l.credit),0);if(Math.abs(totalD-totalC)>.01||totalD<=0)throw new Error(`Unbalanced journal for ${input.refType} ${input.refId}.`);const jid=newId(),jn=await journalNo();await appendRow(SHEETS.financeJournals,{Id:jid,JournalNumber:jn,JournalDate:input.date,JournalType:input.type,ReferenceType:input.refType,ReferenceId:input.refId,Description:input.description,Status:"POSTED",TotalDebit:totalD,TotalCredit:totalC,PostedAt:now(),PostedBy:actor,CreatedAt:now(),CreatedBy:actor,IsActive:true});for(const l of input.lines){const a=await account(l.code);const lid=newId();await appendRow(SHEETS.financeJournalLines,{Id:lid,JournalId:jid,AccountId:a.Id,BranchId:input.branchId||"",CustomerId:input.customerId||"",SupplierId:input.supplierId||"",Description:l.description||input.description,Debit:n(l.debit),Credit:n(l.credit),CreatedAt:now(),CreatedBy:actor,IsActive:true});await appendRow(SHEETS.financeLedgerEntries,{Id:newId(),JournalId:jid,JournalLineId:lid,AccountId:a.Id,AccountCode:a.AccountCode,PostingDate:input.date,ReferenceType:input.refType,ReferenceId:input.refId,BranchId:input.branchId||"",CustomerId:input.customerId||"",SupplierId:input.supplierId||"",Description:l.description||input.description,Debit:n(l.debit),Credit:n(l.credit),CreatedAt:now(),IsActive:true})}return true}
export async function runAutomatedPosting(){const u=await requirePermission("finance.gl.post");const runId=newId();await appendRow(SHEETS.financePostingRuns,{Id:runId,RunNumber:`POST-${Date.now()}`,StartedAt:now(),CompletedAt:"",Status:"RUNNING",SourcesScanned:0,JournalsPosted:0,Errors:0,ErrorSummary:"",RunBy:u.userId,IsActive:true});let scanned=0,posted=0,errors:string[]=[];const safe=async(fn:()=>Promise<boolean>)=>{scanned++;try{if(await fn())posted++}catch(e){errors.push(e instanceof Error?e.message:String(e))}};
 const [sales,invoicePayments,invoices,returns,refunds,supplierInvoices,supplierPayments,payables]=await Promise.all([getRows(SHEETS.salesTransactions,true),getRows(SHEETS.salesInvoicePayments,true),getRows(SHEETS.salesInvoices,true),getRows(SHEETS.salesReturns,true),getRows(SHEETS.salesRefunds,true),getRows(SHEETS.financeSupplierInvoices,true),getRows(SHEETS.financeSupplierPayments,true),getRows(SHEETS.financePayables,true)]);
 for(const s of sales.filter((x:any)=>x.Status==="COMPLETED"&&yes(x.IsActive)))await safe(()=>postJournal(u.userId||"",{date:String(s.CompletedAt||s.CreatedAt).slice(0,10),type:"AUTO_SALE",refType:"POS_SALE",refId:s.Id,description:`POS sale ${s.SaleNumber}`,branchId:s.BranchId,customerId:s.CustomerId,lines:[{code:"1000",debit:n(s.Total)},{code:"4000",credit:n(s.Total)},{code:"5000",debit:n(s.CostTotal)},{code:"1200",credit:n(s.CostTotal)}]}));
 for(const inv of invoices.filter((x:any)=>["ISSUED","PARTIALLY_PAID","PAID"].includes(String(x.Status))&&yes(x.IsActive)))await safe(()=>postJournal(u.userId||"",{date:String(inv.InvoiceDate||inv.CreatedAt).slice(0,10),type:"AUTO_INVOICE",refType:"SALES_INVOICE",refId:inv.Id,description:`Sales invoice ${inv.InvoiceNumber}`,branchId:inv.BranchId,customerId:inv.CustomerId,lines:[{code:"1100",debit:n(inv.Total)},{code:"4000",credit:n(inv.Total)}]}));
 for(const p of invoicePayments.filter((x:any)=>yes(x.IsActive)))await safe(async()=>{const inv=invoices.find((i:any)=>i.Id===p.InvoiceId);return postJournal(u.userId||"",{date:String(p.PaidAt||now()).slice(0,10),type:"AUTO_RECEIPT",refType:"CUSTOMER_PAYMENT",refId:p.Id,description:`Customer payment ${p.Reference||p.Id}`,branchId:inv?.BranchId,customerId:inv?.CustomerId,lines:[{code:"1000",debit:n(p.Amount)},{code:"1100",credit:n(p.Amount)}]})});
 for(const inv of supplierInvoices.filter((x:any)=>["APPROVED","PARTIALLY_PAID","PAID"].includes(String(x.Status))&&yes(x.IsActive)))await safe(()=>postJournal(u.userId||"",{date:String(inv.InvoiceDate||inv.CreatedAt).slice(0,10),type:"AUTO_AP",refType:"SUPPLIER_INVOICE",refId:inv.Id,description:`Supplier invoice ${inv.InvoiceNumber}`,supplierId:inv.SupplierId,lines:[{code:"1200",debit:n(inv.Total)},{code:"2000",credit:n(inv.Total)}]}));
 for(const p of supplierPayments.filter((x:any)=>x.Status==="POSTED"&&yes(x.IsActive)))await safe(async()=>{const py=payables.find((q:any)=>q.Id===p.PayableId);return postJournal(u.userId||"",{date:String(p.PaymentDate||now()).slice(0,10),type:"AUTO_PAYMENT",refType:"SUPPLIER_PAYMENT",refId:p.Id,description:`Supplier payment ${p.Reference||p.Id}`,supplierId:p.SupplierId||py?.SupplierId,lines:[{code:"2000",debit:n(p.Amount)},{code:"1000",credit:n(p.Amount)}]})});
 for(const r of refunds.filter((x:any)=>x.Status==="PROCESSED"&&yes(x.IsActive)))await safe(()=>postJournal(u.userId||"",{date:String(r.ProcessedAt||r.CreatedAt).slice(0,10),type:"AUTO_REFUND",refType:"CUSTOMER_REFUND",refId:r.Id,description:`Customer refund ${r.RefundNumber}`,customerId:r.CustomerId,lines:[{code:"4100",debit:n(r.Amount)},{code:"1000",credit:n(r.Amount)}]}));
 const {updateRow}=await import("@/lib/sheets");await updateRow(SHEETS.financePostingRuns,runId,{CompletedAt:now(),Status:errors.length?"COMPLETED_WITH_ERRORS":"COMPLETED",SourcesScanned:scanned,JournalsPosted:posted,Errors:errors.length,ErrorSummary:errors.slice(0,10).join(" | ")});await writeAudit({userId:u.userId,action:"POST",module:"finance",entityType:"PostingRun",entityId:runId,description:`Automated GL posting: ${posted} journal(s), ${errors.length} error(s)`});["/finance","/finance/journals","/finance/general-ledger","/finance/trial-balance","/finance/posting-center"].forEach(p=>revalidatePath(p));}
export async function createManualJournal(fd:FormData){const u=await requirePermission("finance.journals.post");const date=String(fd.get("date")||new Date().toISOString().slice(0,10)),desc=String(fd.get("description")||"").trim(),debitCode=String(fd.get("debitAccount")||""),creditCode=String(fd.get("creditAccount")||""),amount=n(fd.get("amount"));if(!desc||!debitCode||!creditCode||amount<=0)return;await postJournal(u.userId||"",{date,type:"MANUAL",refType:"MANUAL_JOURNAL",refId:newId(),description:desc,lines:[{code:debitCode,debit:amount},{code:creditCode,credit:amount}]});await writeAudit({userId:u.userId||"",action:"POST",module:"finance",entityType:"Journal",description:`Manual journal: ${desc}`});["/finance/journals","/finance/general-ledger","/finance/trial-balance"].forEach(p=>revalidatePath(p))}
