"use server";
import { revalidatePath } from "next/cache";
import { appendRow,findById,getRows,newId,SHEETS,updateRow } from "@/lib/sheets";
import { requirePermission } from "@/lib/authz";
import { writeAudit } from "@/lib/audit";

export type InventoryActionState={error?:string;success?:string};
const text=(fd:FormData,k:string)=>String(fd.get(k)||"").trim();
const num=(v:any)=>v==null||v===""?0:Number(v);
const now=()=>new Date().toISOString();
const bool=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1";

async function balance(productId:string,warehouseId:string){return (await getRows(SHEETS.inventoryBalances,true)).find((r:any)=>r.ProductId===productId&&r.WarehouseId===warehouseId&&bool(r.IsActive??true))||null}
async function ensureReferences(productId:string,warehouseId:string){const [product,warehouse]=await Promise.all([findById(SHEETS.catalogueProducts,productId),findById(SHEETS.warehouses,warehouseId)]);if(!product||!bool(product.IsActive))throw new Error("Selected product is not active.");if(!warehouse||!bool(warehouse.IsActive))throw new Error("Selected warehouse is not active.");if(!bool(product.TrackInventory??true))throw new Error("This product is not configured for inventory tracking.");return {product,warehouse}}
async function publishInventoryMetrics(){
 const [balances,products,metrics,alerts]=await Promise.all([getRows(SHEETS.inventoryBalances,true),getRows(SHEETS.catalogueProducts),getRows(SHEETS.dashboardMetrics,true),getRows(SHEETS.dashboardAlerts,true)]);
 const active=balances.filter((b:any)=>bool(b.IsActive??true));let value=0,low=0,out=0;for(const b of active){const p=products.find((x:any)=>x.Id===b.ProductId);const on=num(b.QuantityOnHand),reserved=num(b.QuantityReserved),available=on-reserved,cost=num(b.AverageCost||p?.CostPrice),reorder=num(p?.ReorderLevel);value+=on*cost;if(available<=reorder)low++;if(available<=0)out++}
 for(const [key,val] of [["inventory.value",value],["inventory.low_stock",low],["inventory.out_of_stock",out]] as const){const existing=metrics.find((m:any)=>m.MetricKey===key&&!m.BranchId&&bool(m.IsCurrent??true));if(existing)await updateRow(SHEETS.dashboardMetrics,existing.Id,{NumericValue:val,UpdatedAt:now(),IsCurrent:true,IsActive:true});else await appendRow(SHEETS.dashboardMetrics,{Id:newId(),MetricKey:key,CompanyId:"",BranchId:"",NumericValue:val,TextValue:"",PeriodStart:"",PeriodEnd:"",IsCurrent:true,UpdatedAt:now(),IsActive:true})}
 const existingAlert=alerts.find((a:any)=>a.AlertKey==="inventory.low_stock"&&bool(a.IsActive??true));if(low>0){if(existingAlert)await updateRow(SHEETS.dashboardAlerts,existingAlert.Id,{Severity:out>0?"DANGER":"WARNING",Title:"Inventory attention required",Message:`${low} stock positions are at/below reorder level; ${out} are out of stock.`,Link:"/inventory/reorder",ResolvedAt:"",IsActive:true});else await appendRow(SHEETS.dashboardAlerts,{Id:newId(),CompanyId:"",BranchId:"",AlertKey:"inventory.low_stock",Severity:out>0?"DANGER":"WARNING",Title:"Inventory attention required",Message:`${low} stock positions are at/below reorder level; ${out} are out of stock.`,Link:"/inventory/reorder",IsActive:true,CreatedAt:now(),ResolvedAt:""})}else if(existingAlert)await updateRow(SHEETS.dashboardAlerts,existingAlert.Id,{IsActive:false,ResolvedAt:now()});
}
async function postMovement(input:{productId:string;warehouseId:string;quantity:number;movementType:string;unitCost?:number;referenceType?:string;referenceId?:string;reason?:string;actor:string;reservedDelta?:number;damagedDelta?:number}){
 const {product,warehouse}=await ensureReferences(input.productId,input.warehouseId);let b=await balance(input.productId,input.warehouseId);const oldOn=num(b?.QuantityOnHand),oldReserved=num(b?.QuantityReserved),oldDamaged=num(b?.QuantityDamaged),delta=input.quantity,resDelta=input.reservedDelta||0,damDelta=input.damagedDelta||0;const newOn=oldOn+delta,newReserved=oldReserved+resDelta,newDamaged=oldDamaged+damDelta;if(newOn<0&&!bool(warehouse.AllowNegativeStock))throw new Error(`Insufficient stock. ${product.Name} has ${oldOn} units on hand in ${warehouse.Name}.`);if(newReserved<0)throw new Error("Reserved quantity cannot become negative.");if(newReserved>newOn)throw new Error("Reserved quantity cannot exceed stock on hand.");if(newDamaged<0)throw new Error("Damaged quantity cannot become negative.");const cost=input.unitCost&&input.unitCost>0?input.unitCost:num(b?.AverageCost||product.CostPrice);if(b)await updateRow(SHEETS.inventoryBalances,b.Id,{QuantityOnHand:newOn,QuantityReserved:newReserved,QuantityDamaged:newDamaged,AverageCost:cost,LastMovementAt:now(),UpdatedAt:now(),UpdatedBy:input.actor,IsActive:true});else{const id=newId();await appendRow(SHEETS.inventoryBalances,{Id:id,ProductId:input.productId,WarehouseId:input.warehouseId,QuantityOnHand:newOn,QuantityReserved:newReserved,QuantityDamaged:newDamaged,AverageCost:cost,LastMovementAt:now(),CreatedAt:now(),CreatedBy:input.actor,UpdatedAt:now(),UpdatedBy:input.actor,IsActive:true});b={Id:id}}
 await appendRow(SHEETS.inventoryMovements,{Id:newId(),ProductId:input.productId,WarehouseId:input.warehouseId,MovementType:input.movementType,Quantity:delta,ReservedDelta:resDelta,DamagedDelta:damDelta,UnitCost:cost,ReferenceType:input.referenceType||"",ReferenceId:input.referenceId||"",Reason:input.reason||"",BalanceAfter:newOn,OccurredAt:now(),CreatedAt:now(),CreatedBy:input.actor,IsActive:true});
 return {newOn,cost,balanceId:b.Id};
}
function refresh(){["/inventory","/inventory/movements","/inventory/transfers","/inventory/adjustments","/inventory/damaged","/inventory/reorder","/dashboard"].forEach((path)=>revalidatePath(path))}

export async function createOpeningStock(_:InventoryActionState,fd:FormData):Promise<InventoryActionState>{const actor=await requirePermission("inventory.opening.create");const productId=text(fd,"productId"),warehouseId=text(fd,"warehouseId"),quantity=num(text(fd,"quantity")),unitCost=num(text(fd,"unitCost"));if(!productId||!warehouseId||quantity<=0)return {error:"Product, warehouse and a quantity greater than zero are required."};try{const prior=(await getRows(SHEETS.inventoryOpening,true)).some((r:any)=>r.ProductId===productId&&r.WarehouseId===warehouseId&&bool(r.IsActive??true));if(prior)return {error:"Opening stock has already been posted for this product and warehouse. Use a stock adjustment for corrections."};const id=newId();await appendRow(SHEETS.inventoryOpening,{Id:id,ProductId:productId,WarehouseId:warehouseId,Quantity:quantity,UnitCost:unitCost,Reference:text(fd,"reference"),Notes:text(fd,"notes"),PostedAt:now(),CreatedAt:now(),CreatedBy:actor.userId,IsActive:true});await postMovement({productId,warehouseId,quantity,movementType:"OPENING_STOCK",unitCost,referenceType:"OPENING_STOCK",referenceId:id,reason:text(fd,"notes")||"Opening stock",actor:actor.userId||""});await writeAudit({userId:actor.userId,action:"POST",module:"inventory",entityType:"OpeningStock",entityId:id,description:`Posted opening stock of ${quantity} units`});await publishInventoryMetrics();refresh();return {success:"Opening stock posted successfully."}}catch(e){return {error:e instanceof Error?e.message:"Unable to post opening stock."}}}

export async function createAdjustment(_:InventoryActionState,fd:FormData):Promise<InventoryActionState>{const actor=await requirePermission("inventory.adjustments.create");const productId=text(fd,"productId"),warehouseId=text(fd,"warehouseId"),quantity=num(text(fd,"quantity")),direction=text(fd,"direction");if(!productId||!warehouseId||quantity<=0)return {error:"Product, warehouse and quantity are required."};if(!text(fd,"reason"))return {error:"A reason is required for every stock adjustment."};const signed=direction==="DECREASE"?-quantity:quantity;try{const id=newId();await appendRow(SHEETS.inventoryAdjustments,{Id:id,ProductId:productId,WarehouseId:warehouseId,AdjustmentType:direction,Quantity:signed,Reason:text(fd,"reason"),Reference:text(fd,"reference"),Status:"POSTED",CreatedAt:now(),CreatedBy:actor.userId,ApprovedAt:now(),ApprovedBy:actor.userId,IsActive:true});await postMovement({productId,warehouseId,quantity:signed,movementType:"ADJUSTMENT",referenceType:"ADJUSTMENT",referenceId:id,reason:text(fd,"reason"),actor:actor.userId||""});await writeAudit({userId:actor.userId,action:"POST",module:"inventory",entityType:"StockAdjustment",entityId:id,description:`Posted ${direction.toLowerCase()} adjustment of ${quantity} units`});await publishInventoryMetrics();refresh();return {success:"Stock adjustment posted successfully."}}catch(e){return {error:e instanceof Error?e.message:"Unable to post stock adjustment."}}}

export async function createTransfer(_:InventoryActionState,fd:FormData):Promise<InventoryActionState>{const actor=await requirePermission("inventory.transfers.create");const productId=text(fd,"productId"),source=text(fd,"sourceWarehouseId"),destination=text(fd,"destinationWarehouseId"),quantity=num(text(fd,"quantity"));if(!productId||!source||!destination||quantity<=0)return {error:"Product, source, destination and quantity are required."};if(source===destination)return {error:"Source and destination warehouses must be different."};try{await ensureReferences(productId,source);await ensureReferences(productId,destination);const src=await balance(productId,source);if(num(src?.QuantityOnHand)-num(src?.QuantityReserved)<quantity)return {error:"Insufficient available stock in the source warehouse."};const id=newId(),number=`TRF-${Date.now().toString().slice(-8)}`;await appendRow(SHEETS.inventoryTransfers,{Id:id,TransferNumber:number,SourceWarehouseId:source,DestinationWarehouseId:destination,Status:"IN_TRANSIT",Notes:text(fd,"notes"),RequestedAt:now(),DispatchedAt:now(),ReceivedAt:"",CreatedAt:now(),CreatedBy:actor.userId,IsActive:true});await appendRow(SHEETS.inventoryTransferLines,{Id:newId(),TransferId:id,ProductId:productId,QuantityRequested:quantity,QuantityDispatched:quantity,QuantityReceived:0,UnitCost:num(src?.AverageCost),CreatedAt:now(),IsActive:true});await postMovement({productId,warehouseId:source,quantity:-quantity,movementType:"TRANSFER_OUT",unitCost:num(src?.AverageCost),referenceType:"TRANSFER",referenceId:id,reason:`Transfer ${number} dispatched`,actor:actor.userId||""});await writeAudit({userId:actor.userId,action:"DISPATCH",module:"inventory",entityType:"StockTransfer",entityId:id,description:`Dispatched ${number}`});await publishInventoryMetrics();refresh();return {success:`Transfer ${number} dispatched. Receive it at the destination to complete the movement.`}}catch(e){return {error:e instanceof Error?e.message:"Unable to create transfer."}}}

export async function receiveTransfer(_:InventoryActionState,fd:FormData):Promise<InventoryActionState>{const actor=await requirePermission("inventory.transfers.receive");const id=text(fd,"id");try{const transfer=await findById(SHEETS.inventoryTransfers,id);if(!transfer)return {error:"Transfer not found."};if(transfer.Status!=="IN_TRANSIT")return {error:"Only transfers in transit can be received."};const lines=(await getRows(SHEETS.inventoryTransferLines,true)).filter((r:any)=>r.TransferId===id&&bool(r.IsActive??true));for(const line of lines){const qty=num(line.QuantityDispatched);await postMovement({productId:line.ProductId,warehouseId:transfer.DestinationWarehouseId,quantity:qty,movementType:"TRANSFER_IN",unitCost:num(line.UnitCost),referenceType:"TRANSFER",referenceId:id,reason:`Transfer ${transfer.TransferNumber} received`,actor:actor.userId||""});await updateRow(SHEETS.inventoryTransferLines,line.Id,{QuantityReceived:qty})}await updateRow(SHEETS.inventoryTransfers,id,{Status:"RECEIVED",ReceivedAt:now()});await writeAudit({userId:actor.userId,action:"RECEIVE",module:"inventory",entityType:"StockTransfer",entityId:id,description:`Received ${transfer.TransferNumber}`});await publishInventoryMetrics();refresh();return {success:`${transfer.TransferNumber} received successfully.`}}catch(e){return {error:e instanceof Error?e.message:"Unable to receive transfer."}}}

export async function reportDamage(_:InventoryActionState,fd:FormData):Promise<InventoryActionState>{const actor=await requirePermission("inventory.damaged.create");const productId=text(fd,"productId"),warehouseId=text(fd,"warehouseId"),quantity=num(text(fd,"quantity"));if(!productId||!warehouseId||quantity<=0)return {error:"Product, warehouse and quantity are required."};if(!text(fd,"reason"))return {error:"Damage reason is required."};try{const b=await balance(productId,warehouseId);if(num(b?.QuantityOnHand)-num(b?.QuantityReserved)<quantity)return {error:"Insufficient available stock to move into damaged stock."};const id=newId();await appendRow(SHEETS.inventoryDamaged,{Id:id,ProductId:productId,WarehouseId:warehouseId,Quantity:quantity,Reason:text(fd,"reason"),Condition:text(fd,"condition")||"DAMAGED",Disposition:"PENDING",Notes:text(fd,"notes"),CreatedAt:now(),CreatedBy:actor.userId,ResolvedAt:"",ResolvedBy:"",IsActive:true});await postMovement({productId,warehouseId,quantity:-quantity,movementType:"DAMAGE",damagedDelta:quantity,referenceType:"DAMAGE",referenceId:id,reason:text(fd,"reason"),actor:actor.userId||""});await writeAudit({userId:actor.userId,action:"POST",module:"inventory",entityType:"DamagedStock",entityId:id,description:`Moved ${quantity} units to damaged stock`});await publishInventoryMetrics();refresh();return {success:"Damaged stock recorded successfully."}}catch(e){return {error:e instanceof Error?e.message:"Unable to record damaged stock."}}}

export async function createReservation(_:InventoryActionState,fd:FormData):Promise<InventoryActionState>{const actor=await requirePermission("inventory.reservations.create");const productId=text(fd,"productId"),warehouseId=text(fd,"warehouseId"),quantity=num(text(fd,"quantity"));if(!productId||!warehouseId||quantity<=0)return {error:"Product, warehouse and quantity are required."};try{const b=await balance(productId,warehouseId);if(num(b?.QuantityOnHand)-num(b?.QuantityReserved)<quantity)return {error:"Insufficient available stock to reserve."};const id=newId();await appendRow(SHEETS.inventoryReservations,{Id:id,ProductId:productId,WarehouseId:warehouseId,Quantity:quantity,ReferenceType:text(fd,"referenceType")||"MANUAL",ReferenceId:text(fd,"referenceId"),CustomerReference:text(fd,"customerReference"),Status:"ACTIVE",ExpiresAt:text(fd,"expiresAt"),CreatedAt:now(),CreatedBy:actor.userId,ReleasedAt:"",ReleasedBy:"",IsActive:true});await postMovement({productId,warehouseId,quantity:0,reservedDelta:quantity,movementType:"RESERVATION",referenceType:"RESERVATION",referenceId:id,reason:"Stock reserved",actor:actor.userId||""});await writeAudit({userId:actor.userId,action:"RESERVE",module:"inventory",entityType:"Reservation",entityId:id,description:`Reserved ${quantity} units`});await publishInventoryMetrics();refresh();return {success:"Stock reserved successfully."}}catch(e){return {error:e instanceof Error?e.message:"Unable to reserve stock."}}}

export async function releaseReservation(_:InventoryActionState,fd:FormData):Promise<InventoryActionState>{const actor=await requirePermission("inventory.reservations.release");const id=text(fd,"id");try{const r=await findById(SHEETS.inventoryReservations,id);if(!r||r.Status!=="ACTIVE")return {error:"Active reservation not found."};await postMovement({productId:r.ProductId,warehouseId:r.WarehouseId,quantity:0,reservedDelta:-num(r.Quantity),movementType:"RESERVATION_RELEASE",referenceType:"RESERVATION",referenceId:id,reason:"Reservation released",actor:actor.userId||""});await updateRow(SHEETS.inventoryReservations,id,{Status:"RELEASED",ReleasedAt:now(),ReleasedBy:actor.userId,IsActive:false});await writeAudit({userId:actor.userId,action:"RELEASE",module:"inventory",entityType:"Reservation",entityId:id,description:`Released reservation of ${r.Quantity} units`});await publishInventoryMetrics();refresh();return {success:"Reservation released."}}catch(e){return {error:e instanceof Error?e.message:"Unable to release reservation."}}}
