"use server";
import {revalidatePath} from "next/cache";
import {appendRow,findById,getRows,newId,SHEETS,updateRow} from "@/lib/sheets";
import {requirePermission} from "@/lib/authz";
import {writeAudit} from "@/lib/audit";
const now=()=>new Date().toISOString(),n=(v:any)=>Number(v||0);
const refresh=()=>["/finance/period-close","/finance/accruals","/finance/journals","/finance/general-ledger","/finance/trial-balance"].forEach(p=>revalidatePath(p));
const checklist=["Complete GL automated posting","Reconcile cash and bank balances","Review accounts receivable ageing","Review accounts payable ageing","Complete inventory/stocktake adjustments","Review supplier invoice match exceptions","Post accruals and prepayments","Review VAT/WHT registers","Validate trial balance","Generate management accounts","Management review and sign-off"];
export async function startClose(fd:FormData){const u=await requirePermission("finance.period-close.manage"),periodId=String(fd.get("periodId")||"");const p=await findById(SHEETS.financePeriods,periodId);if(!p)throw new Error("Accounting period not found.");const existing=(await getRows(SHEETS.financeCloseCycles,true)).find((x:any)=>x.PeriodId===periodId&&String(x.IsActive??true)!=="false"&&!['CLOSED','CANCELLED'].includes(String(x.Status)));if(existing)throw new Error("An active close cycle already exists for this period.");const id=newId(),rows=await getRows(SHEETS.financeCloseCycles,true);await appendRow(SHEETS.financeCloseCycles,{Id:id,CloseNumber:`CLOSE-${String(rows.length+1).padStart(5,'0')}`,PeriodId:periodId,CloseType:String(fd.get("closeType")||"MONTH_END"),Status:"IN_PROGRESS",StartedAt:now(),StartedBy:u.userId,SubmittedAt:"",SubmittedBy:"",ApprovedAt:"",ApprovedBy:"",ClosedAt:"",ClosedBy:"",ReopenedAt:"",ReopenedBy:"",Notes:String(fd.get("notes")||""),CreatedAt:now(),UpdatedAt:now(),IsActive:true});for(let i=0;i<checklist.length;i++)await appendRow(SHEETS.financeCloseChecklist,{Id:newId(),CloseCycleId:id,ItemCode:`CHK-${String(i+1).padStart(2,'0')}`,ItemName:checklist[i],SortOrder:(i+1)*10,Status:"PENDING",CompletedAt:"",CompletedBy:"",EvidenceReference:"",Notes:"",CreatedAt:now(),UpdatedAt:now(),IsActive:true});await writeAudit({userId:u.userId,action:"CREATE",module:"finance",entityType:"CloseCycle",entityId:id,description:`Started period close for ${p.Name}`});refresh()}
export async function completeChecklist(fd:FormData){const u=await requirePermission("finance.period-close.manage"),id=String(fd.get("id")||"");if(!id)return;await updateRow(SHEETS.financeCloseChecklist,id,{Status:"COMPLETED",CompletedAt:now(),CompletedBy:u.userId,EvidenceReference:String(fd.get("evidence")||""),Notes:String(fd.get("notes")||""),UpdatedAt:now()});refresh()}
export async function submitClose(fd:FormData){const u=await requirePermission("finance.period-close.manage"),id=String(fd.get("id")||"");const c=await findById(SHEETS.financeCloseCycles,id);if(!c)return;const items=(await getRows(SHEETS.financeCloseChecklist,true)).filter((x:any)=>x.CloseCycleId===id&&String(x.IsActive??true)!=="false");if(items.some((x:any)=>x.Status!=="COMPLETED"))throw new Error("Complete all close checklist items before submitting.");const p=await findById(SHEETS.financePeriods,c.PeriodId);if(!p)throw new Error("Accounting period not found.");const journals=(await getRows(SHEETS.financeJournals,true)).filter((j:any)=>j.Status==="POSTED"&&String(j.JournalDate)>=String(p.StartDate)&&String(j.JournalDate)<=String(p.EndDate)),ids=new Set(journals.map((j:any)=>j.Id)),lines=(await getRows(SHEETS.financeJournalLines,true)).filter((l:any)=>ids.has(l.JournalId)),d=lines.reduce((s:number,l:any)=>s+n(l.Debit),0),cr=lines.reduce((s:number,l:any)=>s+n(l.Credit),0);if(Math.abs(d-cr)>.01)throw new Error("Trial balance is not balanced for this period.");await updateRow(SHEETS.financeCloseCycles,id,{Status:"PENDING_APPROVAL",SubmittedAt:now(),SubmittedBy:u.userId,UpdatedAt:now()});await appendRow(SHEETS.financeCloseApprovals,{Id:newId(),CloseCycleId:id,Decision:"PENDING",Notes:"",RequestedAt:now(),RequestedBy:u.userId,DecidedAt:"",DecidedBy:"",IsActive:true});refresh()}
export async function approveAndClose(fd:FormData){const u=await requirePermission("finance.period-close.approve"),id=String(fd.get("id")||"");const c=await findById(SHEETS.financeCloseCycles,id);if(!c||c.Status!=="PENDING_APPROVAL")throw new Error("Close cycle is not pending approval.");await updateRow(SHEETS.financeCloseCycles,id,{Status:"CLOSED",ApprovedAt:now(),ApprovedBy:u.userId,ClosedAt:now(),ClosedBy:u.userId,UpdatedAt:now()});await updateRow(SHEETS.financePeriods,c.PeriodId,{Status:"CLOSED",ClosedAt:now(),ClosedBy:u.userId});const a=(await getRows(SHEETS.financeCloseApprovals,true)).find((x:any)=>x.CloseCycleId===id&&x.Decision==="PENDING");if(a)await updateRow(SHEETS.financeCloseApprovals,a.Id,{Decision:"APPROVED",DecidedAt:now(),DecidedBy:u.userId,Notes:String(fd.get("notes")||"")});await appendRow(SHEETS.financeCloseEvents,{Id:newId(),CloseCycleId:id,EventType:"PERIOD_CLOSED",Description:"Accounting period closed and locked",OccurredAt:now(),OccurredBy:u.userId,IsActive:true});await writeAudit({userId:u.userId,action:"CLOSE",module:"finance",entityType:"AccountingPeriod",entityId:c.PeriodId,description:"Closed accounting period"});refresh()}
export async function reopenPeriod(fd:FormData){const u=await requirePermission("finance.period-close.reopen"),id=String(fd.get("id")||""),reason=String(fd.get("reason")||"").trim();if(!reason)throw new Error("Reopen reason is required.");const c=await findById(SHEETS.financeCloseCycles,id);if(!c||c.Status!=="CLOSED")throw new Error("Only a closed period can be reopened.");await updateRow(SHEETS.financeCloseCycles,id,{Status:"REOPENED",ReopenedAt:now(),ReopenedBy:u.userId,UpdatedAt:now(),Notes:[c.Notes,`REOPEN: ${reason}`].filter(Boolean).join(" | ")});await updateRow(SHEETS.financePeriods,c.PeriodId,{Status:"OPEN",ReopenedAt:now(),ReopenedBy:u.userId});await appendRow(SHEETS.financeCloseEvents,{Id:newId(),CloseCycleId:id,EventType:"PERIOD_REOPENED",Description:reason,OccurredAt:now(),OccurredBy:u.userId,IsActive:true});await writeAudit({userId:u.userId,action:"REOPEN",module:"finance",entityType:"AccountingPeriod",entityId:c.PeriodId,description:`Reopened accounting period: ${reason}`});refresh()}
export async function createAccrual(fd:FormData){const u=await requirePermission("finance.accruals.manage"),periodId=String(fd.get("periodId")||""),amount=n(fd.get("amount"));if(!periodId||amount<=0)return;await appendRow(SHEETS.financeAccruals,{Id:newId(),AccrualNumber:`ACC-${Date.now()}`,PeriodId:periodId,Description:String(fd.get("description")||""),ExpenseAccountId:String(fd.get("expenseAccountId")||""),LiabilityAccountId:String(fd.get("liabilityAccountId")||""),Amount:amount,Status:"DRAFT",JournalId:"",ReversalDate:String(fd.get("reversalDate")||""),CreatedAt:now(),CreatedBy:u.userId,UpdatedAt:now(),UpdatedBy:u.userId,IsActive:true});refresh()}
export async function createPrepayment(fd:FormData){const u=await requirePermission("finance.prepayments.manage"),amount=n(fd.get("amount"));if(amount<=0)return;await appendRow(SHEETS.financePrepayments,{Id:newId(),PrepaymentNumber:`PRE-${Date.now()}`,Description:String(fd.get("description")||""),AssetAccountId:String(fd.get("assetAccountId")||""),ExpenseAccountId:String(fd.get("expenseAccountId")||""),OriginalAmount:amount,RemainingAmount:amount,StartDate:String(fd.get("startDate")||""),EndDate:String(fd.get("endDate")||""),Frequency:String(fd.get("frequency")||"MONTHLY"),Status:"ACTIVE",CreatedAt:now(),CreatedBy:u.userId,UpdatedAt:now(),UpdatedBy:u.userId,IsActive:true});refresh()}
