"use server";
import { revalidatePath } from "next/cache";
import { requirePermission } from "@/lib/authz";
import { writeAudit } from "@/lib/audit";
import { usingGoogleSheets } from "@/lib/data-provider";
import { gsCreateRole,gsSaveRolePermissions } from "@/data/google-services";
import { findById,SHEETS,updateRow } from "@/lib/sheets";
import * as legacy from "@/data/providers/sql-server/legacy/roles-actions";
export type RoleState={error?:string;success?:string};
export async function createRole(_:RoleState,fd:FormData):Promise<RoleState>{if(!usingGoogleSheets())return legacy.createRole(_,fd);const actor=await requirePermission("admin.roles.manage"),name=String(fd.get("name")||"").trim(),description=String(fd.get("description")||"").trim();if(!name)return {error:"Role name is required."};try{const id=await gsCreateRole(name,description);await writeAudit({userId:actor.userId,action:"CREATE",module:"administration",entityType:"Role",entityId:id,description:`Created role ${name}`});revalidatePath("/administration/roles");return {success:"Role created."}}catch(e){return {error:e instanceof Error?e.message:"Unable to create role."}}}
export async function saveRolePermissions(fd:FormData){if(!usingGoogleSheets())return legacy.saveRolePermissions(fd);const actor=await requirePermission("admin.roles.manage"),roleId=String(fd.get("roleId")||""),permissionIds=fd.getAll("permissionId").map(String);await gsSaveRolePermissions(roleId,permissionIds);await writeAudit({userId:actor.userId,action:"UPDATE_PERMISSIONS",module:"administration",entityType:"Role",entityId:roleId,description:`Updated role permissions (${permissionIds.length} granted)`});revalidatePath(`/administration/roles/${roleId}`);revalidatePath("/administration/roles")}
export async function toggleRole(fd:FormData){if(!usingGoogleSheets())return legacy.toggleRole(fd);const actor=await requirePermission("admin.roles.manage"),roleId=String(fd.get("roleId")||""),active=String(fd.get("active"))==="true";const role=await findById(SHEETS.roles,roleId);if(!role||role.Code==="SUPER_ADMIN")return;await updateRow(SHEETS.roles,roleId,{IsActive:active,UpdatedAt:new Date().toISOString()});await writeAudit({userId:actor.userId,action:active?"ACTIVATE":"DEACTIVATE",module:"administration",entityType:"Role",entityId:roleId,description:`${active?"Activated":"Deactivated"} role`});revalidatePath("/administration/roles")}
