"use server";
import {revalidatePath} from "next/cache";
import {appendRow,findById,newId,SHEETS,updateRow} from "@/lib/sheets";
import {requirePermission} from "@/lib/authz";
import {writeAudit} from "@/lib/audit";
const t=(fd:FormData,k:string)=>String(fd.get(k)||"").trim();const n=(v:any)=>Number(v||0);const now=()=>new Date().toISOString();
function refresh(){for(const p of ["/finance/tax","/finance/tax/codes","/finance/tax/profiles","/finance/tax/reports","/finance/tax/fiscal","/finance"])revalidatePath(p)}
export async function createTaxCode(fd:FormData){const u=await requirePermission("tax.configure");const code=t(fd,"code").toUpperCase();if(!code)return;await appendRow(SHEETS.taxCodes,{Id:newId(),Code:code,Name:t(fd,"name"),TaxType:t(fd,"taxType")||"VAT",Rate:n(fd.get("rate")),Treatment:t(fd,"treatment")||"STANDARD",AppliesTo:t(fd,"appliesTo"),Recoverable:t(fd,"recoverable")==="on",EffectiveFrom:t(fd,"effectiveFrom"),EffectiveTo:t(fd,"effectiveTo"),LegalReference:t(fd,"legalReference"),Description:t(fd,"description"),IsDefault:false,CreatedAt:now(),CreatedBy:u.userId,UpdatedAt:now(),UpdatedBy:u.userId,IsActive:true});await writeAudit({userId:u.userId,action:"CREATE",module:"tax",entityType:"TaxCode",entityId:code,description:`Created tax code ${code}`});refresh()}
export async function assignProductTax(fd:FormData){const u=await requirePermission("tax.configure"),productId=t(fd,"productId"),taxCode=t(fd,"taxCode");if(!productId)return;const p=await findById(SHEETS.catalogueProducts,productId);if(!p)return;await updateRow(SHEETS.catalogueProducts,productId,{TaxCode:taxCode,UpdatedAt:now(),UpdatedBy:u.userId});await writeAudit({userId:u.userId,action:"UPDATE",module:"tax",entityType:"ProductTax",entityId:productId,description:`Assigned ${taxCode||'UNCLASSIFIED'} to ${p.Name}`});refresh()}
export async function saveCustomerTaxProfile(fd:FormData){const u=await requirePermission("tax.profiles.manage"),id=t(fd,"id"),customerId=t(fd,"customerId");const patch={CustomerId:customerId,TIN:t(fd,"tin"),VATRegistrationNumber:t(fd,"vatRegistrationNumber"),TaxStatus:t(fd,"taxStatus")||"STANDARD",DefaultTaxCode:t(fd,"defaultTaxCode"),ExemptionId:t(fd,"exemptionId"),WHTApplicable:t(fd,"whtApplicable")==="on",Notes:t(fd,"notes"),UpdatedAt:now(),UpdatedBy:u.userId,IsActive:true};if(id)await updateRow(SHEETS.taxCustomerProfiles,id,patch);else await appendRow(SHEETS.taxCustomerProfiles,{Id:newId(),...patch,CreatedAt:now(),CreatedBy:u.userId});await writeAudit({userId:u.userId,action:id?"UPDATE":"CREATE",module:"tax",entityType:"CustomerTaxProfile",entityId:customerId,description:"Updated customer tax profile"});refresh()}
export async function saveSupplierTaxProfile(fd:FormData){const u=await requirePermission("tax.profiles.manage"),id=t(fd,"id"),supplierId=t(fd,"supplierId");const patch={SupplierId:supplierId,TIN:t(fd,"tin"),VATRegistrationNumber:t(fd,"vatRegistrationNumber"),TaxStatus:t(fd,"taxStatus")||"STANDARD",DefaultTaxCode:t(fd,"defaultTaxCode"),WHTCategory:t(fd,"whtCategory"),WHTRate:n(fd.get("whtRate")),WHTApplicable:t(fd,"whtApplicable")==="on",Notes:t(fd,"notes"),UpdatedAt:now(),UpdatedBy:u.userId,IsActive:true};if(id)await updateRow(SHEETS.taxSupplierProfiles,id,patch);else await appendRow(SHEETS.taxSupplierProfiles,{Id:newId(),...patch,CreatedAt:now(),CreatedBy:u.userId});await writeAudit({userId:u.userId,action:id?"UPDATE":"CREATE",module:"tax",entityType:"SupplierTaxProfile",entityId:supplierId,description:"Updated supplier tax profile"});refresh()}
export async function createVatReturn(fd:FormData){const u=await requirePermission("tax.vat.manage"),periodId=t(fd,"periodId"),period=await findById(SHEETS.financePeriods,periodId);if(!period)return;const id=newId(),number=`VAT-${String(period.PeriodCode||period.Name).replace(/\s+/g,'-')}`;await appendRow(SHEETS.taxVatReturns,{Id:id,ReturnNumber:number,PeriodId:periodId,PeriodStart:period.StartDate,PeriodEnd:period.EndDate,OutputVAT:n(fd.get("outputVAT")),InputVAT:n(fd.get("inputVAT")),NetVAT:n(fd.get("netVAT")),ZeroRatedSales:n(fd.get("zeroRatedSales")),ExemptSales:n(fd.get("exemptSales")),TaxableSales:n(fd.get("taxableSales")),Status:"DRAFT",FiledAt:"",FiledBy:"",Reference:"",Notes:t(fd,"notes"),CreatedAt:now(),CreatedBy:u.userId,UpdatedAt:now(),UpdatedBy:u.userId,IsActive:true});await writeAudit({userId:u.userId,action:"CREATE",module:"tax",entityType:"VATReturn",entityId:id,description:`Prepared VAT return ${number}`});refresh()}
export async function updateFiscalSetting(fd:FormData){const u=await requirePermission("tax.fiscal.manage"),id=t(fd,"id"),value=t(fd,"value");if(!id)return;await updateRow(SHEETS.taxFiscalSettings,id,{SettingValue:value,UpdatedAt:now(),UpdatedBy:u.userId});await writeAudit({userId:u.userId,action:"UPDATE",module:"tax",entityType:"FiscalSetting",entityId:id,description:"Updated tax/fiscal setting"});refresh()}
