"use server";
import { revalidatePath } from "next/cache";
import { requirePermission } from "@/lib/authz";
import { generateTemporaryPassword,hashPassword,validatePasswordPolicy } from "@/lib/password";
import { writeAudit } from "@/lib/audit";
import { usingGoogleSheets } from "@/lib/data-provider";
import { findById,SHEETS,updateRow,appendRow,newId } from "@/lib/sheets";
import { gsAssignSingleRole,gsCreateUser,gsRevokeUserSessions } from "@/data/google-services";
import * as legacy from "@/data/providers/sql-server/legacy/users-actions";
export type ActionState={error?:string;success?:string;temporaryPassword?:string};
export async function createUser(_:ActionState,fd:FormData):Promise<ActionState>{if(!usingGoogleSheets())return legacy.createUser(_,fd);const actor=await requirePermission("admin.users.manage"),name=String(fd.get("displayName")||"").trim(),email=String(fd.get("email")||"").trim().toLowerCase(),roleId=String(fd.get("roleId")||"");let password=String(fd.get("temporaryPassword")||"");if(!name||!email||!roleId)return {error:"Name, email and role are required."};if(!password)password=generateTemporaryPassword();const policy=validatePasswordPolicy(password);if(policy.length)return {error:`Temporary password must contain ${policy.join(", ")}.`};try{const id=await gsCreateUser({email,name,hash:await hashPassword(password),roleId,actor:actor.userId});await writeAudit({userId:actor.userId,action:"CREATE",module:"administration",entityType:"User",entityId:id,description:`Created user ${email}`});revalidatePath("/administration/users");return {success:"User created successfully. Share the temporary password securely.",temporaryPassword:password}}catch(e){return {error:e instanceof Error?e.message:"Unable to create user."}}}
export async function toggleUser(fd:FormData){if(!usingGoogleSheets())return legacy.toggleUser(fd);const actor=await requirePermission("admin.users.manage"),id=String(fd.get("id")||""),active=String(fd.get("active"))==="true";if(!id||id===actor.userId)return;await updateRow(SHEETS.users,id,{IsActive:active,UpdatedAt:new Date().toISOString(),UpdatedBy:actor.userId});if(!active)await gsRevokeUserSessions(id);await writeAudit({userId:actor.userId,action:active?"ACTIVATE":"DEACTIVATE",module:"administration",entityType:"User",entityId:id,description:`${active?"Activated":"Deactivated"} user account`});revalidatePath("/administration/users")}
export async function unlockUser(fd:FormData){if(!usingGoogleSheets())return legacy.unlockUser(fd);const actor=await requirePermission("admin.users.manage"),id=String(fd.get("id")||"");await updateRow(SHEETS.users,id,{FailedLoginCount:0,LockedUntil:"",UpdatedAt:new Date().toISOString(),UpdatedBy:actor.userId});await writeAudit({userId:actor.userId,action:"UNLOCK",module:"security",entityType:"User",entityId:id,description:"Unlocked user account"});revalidatePath("/administration/users")}
export async function resetUserPassword(_:ActionState,fd:FormData):Promise<ActionState>{if(!usingGoogleSheets())return legacy.resetUserPassword(_,fd);const actor=await requirePermission("admin.users.manage"),id=String(fd.get("userId")||"");let password=String(fd.get("temporaryPassword")||"");if(!password)password=generateTemporaryPassword();const policy=validatePasswordPolicy(password);if(policy.length)return {error:`Temporary password must contain ${policy.join(", ")}.`};const user=await findById(SHEETS.users,id);if(!user)return {error:"User not found."};if(user.PasswordHash)await appendRow(SHEETS.passwordHistory,{Id:newId(),UserId:id,PasswordHash:user.PasswordHash,CreatedAt:new Date().toISOString(),IsActive:true});await updateRow(SHEETS.users,id,{PasswordHash:await hashPassword(password),MustChangePassword:true,FailedLoginCount:0,LockedUntil:"",UpdatedAt:new Date().toISOString(),UpdatedBy:actor.userId});await gsRevokeUserSessions(id);await writeAudit({userId:actor.userId,action:"PASSWORD_RESET",module:"security",entityType:"User",entityId:id,description:"Administrator reset user password"});return {success:"Password reset. The user must change it on next sign in.",temporaryPassword:password}}
export async function updateUser(_:ActionState,fd:FormData):Promise<ActionState>{if(!usingGoogleSheets())return legacy.updateUser(_,fd);const actor=await requirePermission("admin.users.manage"),id=String(fd.get("userId")||""),name=String(fd.get("displayName")||"").trim(),phone=String(fd.get("phone")||"").trim(),jobTitle=String(fd.get("jobTitle")||"").trim(),roleId=String(fd.get("roleId")||"");if(!id||!name||!roleId)return {error:"Name and role are required."};try{await updateRow(SHEETS.users,id,{DisplayName:name,Phone:phone,JobTitle:jobTitle,UpdatedAt:new Date().toISOString(),UpdatedBy:actor.userId});await gsAssignSingleRole(id,roleId,actor.userId);await writeAudit({userId:actor.userId,action:"UPDATE",module:"administration",entityType:"User",entityId:id,description:"Updated user profile and role"});revalidatePath(`/administration/users/${id}`);revalidatePath("/administration/users");return {success:"User details updated."}}catch(e){return {error:e instanceof Error?e.message:"Unable to update user."}}}
