import { usingGoogleSheets } from "@/lib/data-provider";
import * as gs from "@/data/google-services";
import * as sqlData from "@/data/providers/sql-server/legacy/organisation-data";
export const organisationSummary=()=>usingGoogleSheets()?gs.gsOrganisationSummary():sqlData.organisationSummary();
export const getPrimaryCompany=()=>usingGoogleSheets()?gs.gsPrimaryCompany():sqlData.getPrimaryCompany();
export const listBranches=()=>usingGoogleSheets()?gs.gsBranches():sqlData.listBranches();
export const getBranch=(id:string)=>usingGoogleSheets()?gs.gsBranch(id):sqlData.getBranch(id);
export const listWarehouses=(branchId?:string)=>usingGoogleSheets()?gs.gsWarehouses(branchId):sqlData.listWarehouses(branchId);
export const getWarehouse=(id:string)=>usingGoogleSheets()?gs.gsWarehouse(id):sqlData.getWarehouse(id);
export const organisationUsers=()=>usingGoogleSheets()?gs.gsOrganisationUsers():sqlData.organisationUsers();
