import { getRows,SHEETS } from "@/lib/sheets";
const bool=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1";
const num=(v:any)=>v==null||v===""?0:Number(v);
export const inventoryMoney=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n||0);
export async function inventoryLookups(){
 const [products,warehouses,branches]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.warehouses),getRows(SHEETS.branches)]);
 return {products:products.filter(p=>bool(p.IsActive)&&bool(p.TrackInventory??true)).sort((a,b)=>String(a.Name).localeCompare(String(b.Name))),warehouses:warehouses.filter(w=>bool(w.IsActive)).map(w=>({...w,BranchName:branches.find(b=>b.Id===w.BranchId)?.Name||""})).sort((a,b)=>String(a.Name).localeCompare(String(b.Name)))};
}
export async function stockOverview(filters:{q?:string;warehouseId?:string;status?:string}={}){
 const [balances,products,warehouses,branches,books,barcodes]=await Promise.all([getRows(SHEETS.inventoryBalances),getRows(SHEETS.catalogueProducts),getRows(SHEETS.warehouses),getRows(SHEETS.branches),getRows(SHEETS.catalogueBooks),getRows(SHEETS.catalogueBarcodes)]);
 const q=(filters.q||"").toLowerCase().trim();
 const rows=balances.filter(b=>bool(b.IsActive??true)).map(b=>{const p=products.find(x=>x.Id===b.ProductId),w=warehouses.find(x=>x.Id===b.WarehouseId),book=books.find(x=>x.ProductId===b.ProductId),barcode=barcodes.find(x=>x.ProductId===b.ProductId&&bool(x.IsPrimary??true));const on=num(b.QuantityOnHand),reserved=num(b.QuantityReserved),damaged=num(b.QuantityDamaged),available=Math.max(0,on-reserved);const reorder=num(p?.ReorderLevel),safety=num(p?.SafetyStock);return {...b,ProductCode:p?.Code||"",ProductName:p?.Name||"Unknown product",ProductType:p?.ProductType||"",WarehouseName:w?.Name||"Unknown",BranchName:branches.find(x=>x.Id===w?.BranchId)?.Name||"",ISBN:book?.ISBN13||book?.ISBN10||"",Barcode:barcode?.Barcode||"",OnHand:on,Reserved:reserved,Damaged:damaged,Available:available,AverageCost:num(b.AverageCost||p?.CostPrice),StockValue:on*num(b.AverageCost||p?.CostPrice),ReorderLevel:reorder,SafetyStock:safety,LowStock:available<=reorder,OutOfStock:available<=0,RecommendedOrder:Math.max(0,reorder+safety-available)}});
 return rows.filter(r=>(!q||[r.ProductCode,r.ProductName,r.ISBN,r.Barcode,r.WarehouseName].some(v=>String(v).toLowerCase().includes(q)))&&(!filters.warehouseId||r.WarehouseId===filters.warehouseId)&&(!filters.status||filters.status==="ALL"||(filters.status==="LOW"&&r.LowStock)||(filters.status==="OUT"&&r.OutOfStock)||(filters.status==="HEALTHY"&&!r.LowStock))).sort((a,b)=>Number(b.OutOfStock)-Number(a.OutOfStock)||Number(b.LowStock)-Number(a.LowStock)||String(a.ProductName).localeCompare(String(b.ProductName)));
}
export async function inventorySummary(){const rows=await stockOverview();return {skuLocations:rows.length,units:rows.reduce((s,r)=>s+r.OnHand,0),available:rows.reduce((s,r)=>s+r.Available,0),reserved:rows.reduce((s,r)=>s+r.Reserved,0),damaged:rows.reduce((s,r)=>s+r.Damaged,0),value:rows.reduce((s,r)=>s+r.StockValue,0),low:rows.filter(r=>r.LowStock).length,out:rows.filter(r=>r.OutOfStock).length}}
export async function movementHistory(limit=200){const [moves,products,warehouses,users]=await Promise.all([getRows(SHEETS.inventoryMovements),getRows(SHEETS.catalogueProducts),getRows(SHEETS.warehouses),getRows(SHEETS.users)]);return moves.sort((a,b)=>String(b.OccurredAt||b.CreatedAt).localeCompare(String(a.OccurredAt||a.CreatedAt))).slice(0,limit).map(m=>({...m,Quantity:num(m.Quantity),UnitCost:num(m.UnitCost),ProductName:products.find(p=>p.Id===m.ProductId)?.Name||"Unknown",ProductCode:products.find(p=>p.Id===m.ProductId)?.Code||"",WarehouseName:warehouses.find(w=>w.Id===m.WarehouseId)?.Name||"Unknown",CreatedByName:users.find(u=>u.Id===m.CreatedBy)?.DisplayName||"System"}))}
export async function listTransfers(){const [rows,warehouses,users]=await Promise.all([getRows(SHEETS.inventoryTransfers),getRows(SHEETS.warehouses),getRows(SHEETS.users)]);return rows.sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>({...r,SourceName:warehouses.find(w=>w.Id===r.SourceWarehouseId)?.Name||"",DestinationName:warehouses.find(w=>w.Id===r.DestinationWarehouseId)?.Name||"",CreatedByName:users.find(u=>u.Id===r.CreatedBy)?.DisplayName||""}))}
export async function listAdjustments(){const [rows,products,warehouses,users]=await Promise.all([getRows(SHEETS.inventoryAdjustments),getRows(SHEETS.catalogueProducts),getRows(SHEETS.warehouses),getRows(SHEETS.users)]);return rows.sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>({...r,Quantity:num(r.Quantity),ProductName:products.find(p=>p.Id===r.ProductId)?.Name||"",WarehouseName:warehouses.find(w=>w.Id===r.WarehouseId)?.Name||"",CreatedByName:users.find(u=>u.Id===r.CreatedBy)?.DisplayName||""}))}
export async function listDamaged(){const [rows,products,warehouses]=await Promise.all([getRows(SHEETS.inventoryDamaged),getRows(SHEETS.catalogueProducts),getRows(SHEETS.warehouses)]);return rows.filter(r=>bool(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>({...r,Quantity:num(r.Quantity),ProductName:products.find(p=>p.Id===r.ProductId)?.Name||"",ProductCode:products.find(p=>p.Id===r.ProductId)?.Code||"",WarehouseName:warehouses.find(w=>w.Id===r.WarehouseId)?.Name||""}))}
export async function listReservations(){const [rows,products,warehouses]=await Promise.all([getRows(SHEETS.inventoryReservations),getRows(SHEETS.catalogueProducts),getRows(SHEETS.warehouses)]);return rows.filter(r=>bool(r.IsActive??true)&&String(r.Status||"ACTIVE")==="ACTIVE").sort((a,b)=>String(a.ExpiresAt||"").localeCompare(String(b.ExpiresAt||""))).map(r=>({...r,Quantity:num(r.Quantity),ProductName:products.find(p=>p.Id===r.ProductId)?.Name||"",WarehouseName:warehouses.find(w=>w.Id===r.WarehouseId)?.Name||""}))}
