import {getRows,SHEETS} from "@/lib/sheets";
const yes=(v:any)=>v===true||String(v).toLowerCase()==="true"||String(v)==="1";
const n=(v:any)=>Number(v||0);
export const procurementMoney=(v:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(v||0);
export async function procurementLookups(){
 const [products,suppliers,warehouses,links,balances]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.suppliers),getRows(SHEETS.warehouses),getRows(SHEETS.supplierProducts),getRows(SHEETS.inventoryBalances)]);
 return {products:products.filter(x=>yes(x.IsActive??true)),suppliers:suppliers.filter(x=>yes(x.IsActive??true)&&String(x.AccountStatus||"ACTIVE")==="ACTIVE"),warehouses:warehouses.filter(x=>yes(x.IsActive??true)),links:links.filter(x=>yes(x.IsActive??true)),balances:balances.filter(x=>yes(x.IsActive??true))};
}
export async function reorderRequirements(){
 const [products,balances,warehouses,links,suppliers,requestLines,requests]=await Promise.all([getRows(SHEETS.catalogueProducts),getRows(SHEETS.inventoryBalances),getRows(SHEETS.warehouses),getRows(SHEETS.supplierProducts),getRows(SHEETS.suppliers),getRows(SHEETS.procurementRequestLines),getRows(SHEETS.procurementRequests)]);
 const openReqIds=new Set(requests.filter(r=>["DRAFT","SUBMITTED","APPROVED"].includes(String(r.Status))).map(r=>r.Id));
 return balances.filter(b=>yes(b.IsActive??true)).map(b=>{const p=products.find(x=>x.Id===b.ProductId),w=warehouses.find(x=>x.Id===b.WarehouseId);const available=n(b.QuantityOnHand)-n(b.QuantityReserved),reorder=n(p?.ReorderLevel),safety=n(p?.SafetyStock),recommended=Math.max(0,reorder+safety-available);const source=links.filter(l=>l.ProductId===b.ProductId&&yes(l.IsActive??true)).sort((a,b)=>Number(yes(b.IsPreferred))-Number(yes(a.IsPreferred))||n(a.UnitCost)-n(b.UnitCost))[0];const supplier=suppliers.find(s=>s.Id===source?.SupplierId);const requested=requestLines.filter(l=>l.ProductId===b.ProductId&&l.WarehouseId===b.WarehouseId&&openReqIds.has(l.PurchaseRequestId)).reduce((a,l)=>a+n(l.QuantityRequested),0);return {ProductId:b.ProductId,WarehouseId:b.WarehouseId,ProductCode:p?.Code||"",ProductName:p?.Name||"Unknown",WarehouseName:w?.Name||"Unknown",Available:available,ReorderLevel:reorder,SafetyStock:safety,RecommendedOrder:recommended,OpenRequested:requested,NetRequirement:Math.max(0,recommended-requested),SuggestedSupplierId:source?.SupplierId||"",SuggestedSupplier:supplier?.Name||"Unassigned",SuggestedUnitCost:n(source?.UnitCost||p?.CostPrice),LeadTimeDays:n(source?.LeadTimeDays||supplier?.DefaultLeadTimeDays),OutOfStock:available<=0}}).filter(x=>x.RecommendedOrder>0).sort((a,b)=>Number(b.OutOfStock)-Number(a.OutOfStock)||b.NetRequirement-a.NetRequirement);
}
export async function listPurchaseRequests(){const [rows,lines,users,warehouses]=await Promise.all([getRows(SHEETS.procurementRequests),getRows(SHEETS.procurementRequestLines),getRows(SHEETS.users),getRows(SHEETS.warehouses)]);return rows.filter(r=>yes(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>{const ls=lines.filter(l=>l.PurchaseRequestId===r.Id&&yes(l.IsActive??true));return {...r,LineCount:ls.length,EstimatedTotal:ls.reduce((a,l)=>a+n(l.QuantityRequested)*n(l.EstimatedUnitCost),0),RequesterName:users.find(u=>u.Id===r.RequestedBy)?.DisplayName||"System",WarehouseName:warehouses.find(w=>w.Id===r.WarehouseId)?.Name||""}})}
export async function getPurchaseRequest(id:string){const [requests,lines,products,suppliers,warehouses,users]=await Promise.all([getRows(SHEETS.procurementRequests),getRows(SHEETS.procurementRequestLines),getRows(SHEETS.catalogueProducts),getRows(SHEETS.suppliers),getRows(SHEETS.warehouses),getRows(SHEETS.users)]);const request=requests.find(r=>r.Id===id&&yes(r.IsActive??true));if(!request)return null;const mapped=lines.filter(l=>l.PurchaseRequestId===id&&yes(l.IsActive??true)).map(l=>({...l,QuantityRequested:n(l.QuantityRequested),QuantityApproved:n(l.QuantityApproved),EstimatedUnitCost:n(l.EstimatedUnitCost),ProductName:products.find(p=>p.Id===l.ProductId)?.Name||"Unknown",ProductCode:products.find(p=>p.Id===l.ProductId)?.Code||"",SupplierName:suppliers.find(s=>s.Id===l.PreferredSupplierId)?.Name||""}));return {request:{...request,WarehouseName:warehouses.find(w=>w.Id===request.WarehouseId)?.Name||"",RequesterName:users.find(u=>u.Id===request.RequestedBy)?.DisplayName||"",ApproverName:users.find(u=>u.Id===request.ApprovedBy)?.DisplayName||""},lines:mapped};}
export async function listPurchaseOrders(){const [rows,lines,suppliers,warehouses]=await Promise.all([getRows(SHEETS.procurementOrders),getRows(SHEETS.procurementOrderLines),getRows(SHEETS.suppliers),getRows(SHEETS.warehouses)]);return rows.filter(r=>yes(r.IsActive??true)).sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt))).map(r=>{const ls=lines.filter(l=>l.PurchaseOrderId===r.Id&&yes(l.IsActive??true));return {...r,LineCount:ls.length,SupplierName:suppliers.find(s=>s.Id===r.SupplierId)?.Name||"Unknown",WarehouseName:warehouses.find(w=>w.Id===r.WarehouseId)?.Name||"",Total:n(r.Total),ReceivedValue:ls.reduce((a,l)=>a+n(l.QuantityReceived)*n(l.UnitCost),0)}})}
export async function getPurchaseOrder(id:string){const [orders,lines,products,suppliers,warehouses,users]=await Promise.all([getRows(SHEETS.procurementOrders),getRows(SHEETS.procurementOrderLines),getRows(SHEETS.catalogueProducts),getRows(SHEETS.suppliers),getRows(SHEETS.warehouses),getRows(SHEETS.users)]);const order=orders.find(r=>r.Id===id&&yes(r.IsActive??true));if(!order)return null;return {order:{...order,Subtotal:n(order.Subtotal),TaxAmount:n(order.TaxAmount),Total:n(order.Total),SupplierName:suppliers.find(s=>s.Id===order.SupplierId)?.Name||"",WarehouseName:warehouses.find(w=>w.Id===order.WarehouseId)?.Name||"",CreatedByName:users.find(u=>u.Id===order.CreatedBy)?.DisplayName||""},lines:lines.filter(l=>l.PurchaseOrderId===id&&yes(l.IsActive??true)).map(l=>({...l,QuantityOrdered:n(l.QuantityOrdered),QuantityReceived:n(l.QuantityReceived),UnitCost:n(l.UnitCost),LineTotal:n(l.LineTotal),ProductName:products.find(p=>p.Id===l.ProductId)?.Name||"Unknown",ProductCode:products.find(p=>p.Id===l.ProductId)?.Code||""}))};}
export async function procurementSummary(){const [requests,orders,reorder]=await Promise.all([listPurchaseRequests(),listPurchaseOrders(),reorderRequirements()]);return {openRequests:requests.filter(r=>["DRAFT","SUBMITTED"].includes(String(r.Status))).length,pendingApproval:requests.filter(r=>String(r.Status)==="SUBMITTED").length,openPOs:orders.filter(o=>["APPROVED","SENT","PARTIALLY_RECEIVED"].includes(String(o.Status))).length,poValue:orders.filter(o=>["APPROVED","SENT","PARTIALLY_RECEIVED"].includes(String(o.Status))).reduce((a,o)=>a+n(o.Total),0),reorderLines:reorder.length,outOfStock:reorder.filter(r=>r.OutOfStock).length};}
